// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.AgvEfficiencyStatistics;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByOrderId;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByUpperId;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.ExportOrderRecord;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Ids;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Item;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Num;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderCountStatistics;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderEfficiencyStatistics;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderIds;
using RIoT.Sdk.Generated.Order.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord
{
    /// <summary>
    /// Builds and executes requests for operations under \api\order\v1\orderRecord
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrderRecordRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The agvEfficiencyStatistics property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.AgvEfficiencyStatistics.AgvEfficiencyStatisticsRequestBuilder AgvEfficiencyStatistics
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.AgvEfficiencyStatistics.AgvEfficiencyStatisticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The detailByOrderId property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByOrderId.DetailByOrderIdRequestBuilder DetailByOrderId
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByOrderId.DetailByOrderIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The detailByUpperId property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByUpperId.DetailByUpperIdRequestBuilder DetailByUpperId
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByUpperId.DetailByUpperIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exportOrderRecord property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.ExportOrderRecord.ExportOrderRecordRequestBuilder ExportOrderRecord
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.ExportOrderRecord.ExportOrderRecordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ids property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Ids.IdsRequestBuilder Ids
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Ids.IdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The num property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Num.NumRequestBuilder Num
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Num.NumRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The old property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.OldRequestBuilder Old
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.OldRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orderCountStatistics property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderCountStatistics.OrderCountStatisticsRequestBuilder OrderCountStatistics
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderCountStatistics.OrderCountStatisticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orderEfficiencyStatistics property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderEfficiencyStatistics.OrderEfficiencyStatisticsRequestBuilder OrderEfficiencyStatistics
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderEfficiencyStatistics.OrderEfficiencyStatisticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orderIds property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderIds.OrderIdsRequestBuilder OrderIds
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderIds.OrderIdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the RIoT.Sdk.Generated.Order.api.order.v1.orderRecord.item collection</summary>
        /// <param name="position">id</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Item.OrderRecordItemRequestBuilder"/></returns>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Item.OrderRecordItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Item.OrderRecordItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the RIoT.Sdk.Generated.Order.api.order.v1.orderRecord.item collection</summary>
        /// <param name="position">id</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Item.OrderRecordItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Item.OrderRecordItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Item.OrderRecordItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrderRecordRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/order/v1/orderRecord?pageNum={pageNum}&pageSize={pageSize}{&endStationName*,endStationNo*,endTime*,executeVehicleKey*,executeVehicleName*,filterBySource*,filterByState,order*,orderBy*,orderType,query*,startStationName*,startStationNo*,startTime*,userId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrderRecordRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/order/v1/orderRecord?pageNum={pageNum}&pageSize={pageSize}{&endStationName*,endStationNo*,endTime*,executeVehicleKey*,executeVehicleName*,filterBySource*,filterByState,order*,orderBy*,orderType,query*,startStationName*,startStationNo*,startTime*,userId*}", rawUrl)
        {
        }
        /// <summary>
        /// 筛选条件分页查询订单列表
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Models.ResponseMsg_Of_Page_Of_OrderRecordObject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RIoT.Sdk.Generated.Order.Models.ResponseMsg_Of_Page_Of_OrderRecordObject?> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder.OrderRecordRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RIoT.Sdk.Generated.Order.Models.ResponseMsg_Of_Page_Of_OrderRecordObject> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder.OrderRecordRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::RIoT.Sdk.Generated.Order.Models.ResponseMsg_Of_Page_Of_OrderRecordObject>(requestInfo, global::RIoT.Sdk.Generated.Order.Models.ResponseMsg_Of_Page_Of_OrderRecordObject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 筛选条件分页查询订单列表
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder.OrderRecordRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder.OrderRecordRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 筛选条件分页查询订单列表
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrderRecordRequestBuilderGetQueryParameters 
        {
            /// <summary>终点名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("endStationName")]
            public string? EndStationName { get; set; }
#nullable restore
#else
            [QueryParameter("endStationName")]
            public string EndStationName { get; set; }
#endif
            /// <summary>终点编号</summary>
            [QueryParameter("endStationNo")]
            public int? EndStationNo { get; set; }
            /// <summary>订单执行时间查-结束  yyyy-MM-dd HH:mm:ss</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("endTime")]
            public string? EndTime { get; set; }
#nullable restore
#else
            [QueryParameter("endTime")]
            public string EndTime { get; set; }
#endif
            /// <summary>执行的车辆id：</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("executeVehicleKey")]
            public string? ExecuteVehicleKey { get; set; }
#nullable restore
#else
            [QueryParameter("executeVehicleKey")]
            public string ExecuteVehicleKey { get; set; }
#endif
            /// <summary>执行的车辆名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("executeVehicleName")]
            public string? ExecuteVehicleName { get; set; }
#nullable restore
#else
            [QueryParameter("executeVehicleName")]
            public string ExecuteVehicleName { get; set; }
#endif
            /// <summary>订单来源过滤器：1:WMS；2:FMS；</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filterBySource")]
            public string? FilterBySource { get; set; }
#nullable restore
#else
            [QueryParameter("filterBySource")]
            public string FilterBySource { get; set; }
#endif
            /// <summary>订单状态过滤器： 1 QUEUEING 队列中 , 2 CANCELLED 已取消, 3 EXECUTING 执行中, 4 FAILED 已失败, 5 SUCCESS 已完成, 6 DELETED  已移除, 7 PAUSED已暂停 ,8 SUSPENDED 已移除，9 HEAD 挂起, 10 队列优先执行</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filterByState")]
            public string[]? FilterByState { get; set; }
#nullable restore
#else
            [QueryParameter("filterByState")]
            public string[] FilterByState { get; set; }
#endif
            /// <summary>正序倒序（DESC为降序，ASC为正序）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>排序的列名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderBy")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("orderBy")]
            public string OrderBy { get; set; }
#endif
            /// <summary>订单类型 1 NORMAL 工作订单, 2 CHARGE 充电订单 , 3 CMD 停靠订单 4 MAINTAIN 电池保养</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderType")]
            public string[]? OrderType { get; set; }
#nullable restore
#else
            [QueryParameter("orderType")]
            public string[] OrderType { get; set; }
#endif
            /// <summary>页码</summary>
            [QueryParameter("pageNum")]
            public int? PageNum { get; set; }
            /// <summary>页大小</summary>
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
            /// <summary>输入订单ID或订单名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>订单起点名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("startStationName")]
            public string? StartStationName { get; set; }
#nullable restore
#else
            [QueryParameter("startStationName")]
            public string StartStationName { get; set; }
#endif
            /// <summary>订单起点编号</summary>
            [QueryParameter("startStationNo")]
            public int? StartStationNo { get; set; }
            /// <summary>订单执行时间查询-开始  yyyy-MM-dd HH:mm:ss</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("startTime")]
            public string? StartTime { get; set; }
#nullable restore
#else
            [QueryParameter("startTime")]
            public string StartTime { get; set; }
#endif
            /// <summary>用户id</summary>
            [QueryParameter("userId")]
            public int? UserId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrderRecordRequestBuilderGetRequestConfiguration : RequestConfiguration<global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder.OrderRecordRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
