// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Device.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query
{
    /// <summary>
    /// Builds and executes requests for operations under \api\device\v1\devices\query
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QueryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query.QueryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device/v1/devices/query{?pageNum*,pageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query.QueryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device/v1/devices/query{?pageNum*,pageSize*}", rawUrl)
        {
        }
        /// <summary>
        /// getDevices
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Models.ResponseMsg_Of_Page_Of_DeviceObject"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RIoT.Sdk.Generated.Device.Models.ResponseMsg_Of_Page_Of_DeviceObject?> PostAsync(global::RIoT.Sdk.Generated.Device.Models.DeviceDto body, Action<RequestConfiguration<global::RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query.QueryRequestBuilder.QueryRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RIoT.Sdk.Generated.Device.Models.ResponseMsg_Of_Page_Of_DeviceObject> PostAsync(global::RIoT.Sdk.Generated.Device.Models.DeviceDto body, Action<RequestConfiguration<global::RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query.QueryRequestBuilder.QueryRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::RIoT.Sdk.Generated.Device.Models.ResponseMsg_Of_Page_Of_DeviceObject>(requestInfo, global::RIoT.Sdk.Generated.Device.Models.ResponseMsg_Of_Page_Of_DeviceObject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// getDevices
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::RIoT.Sdk.Generated.Device.Models.DeviceDto body, Action<RequestConfiguration<global::RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query.QueryRequestBuilder.QueryRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::RIoT.Sdk.Generated.Device.Models.DeviceDto body, Action<RequestConfiguration<global::RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query.QueryRequestBuilder.QueryRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query.QueryRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query.QueryRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query.QueryRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// getDevices
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QueryRequestBuilderPostQueryParameters 
        {
            /// <summary>pageNum</summary>
            [QueryParameter("pageNum")]
            public int? PageNum { get; set; }
            /// <summary>pageSize</summary>
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QueryRequestBuilderPostRequestConfiguration : RequestConfiguration<global::RIoT.Sdk.Generated.Device.Api.Device.V1.Devices.Query.QueryRequestBuilder.QueryRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
