// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Device.Api.Device.V1.Runtime.Properties.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.Device.Api.Device.V1.Runtime.Properties
{
    /// <summary>
    /// Builds and executes requests for operations under \api\device\v1\runtime\properties
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PropertiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the RIoT.Sdk.Generated.Device.api.device.v1.runtime.properties.item collection</summary>
        /// <param name="position">deviceKey</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Runtime.Properties.Item.WithDeviceKeyItemRequestBuilder"/></returns>
        public global::RIoT.Sdk.Generated.Device.Api.Device.V1.Runtime.Properties.Item.WithDeviceKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("deviceKey", position);
                return new global::RIoT.Sdk.Generated.Device.Api.Device.V1.Runtime.Properties.Item.WithDeviceKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Runtime.Properties.PropertiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device/v1/runtime/properties", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Runtime.Properties.PropertiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device/v1/runtime/properties", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
