// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Device.Api.Device.V1.Group.DeleteDeviceGroupById.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.Device.Api.Device.V1.Group.DeleteDeviceGroupById
{
    /// <summary>
    /// Builds and executes requests for operations under \api\device\v1\group\deleteDeviceGroupById
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeleteDeviceGroupByIdRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the RIoT.Sdk.Generated.Device.api.device.v1.group.deleteDeviceGroupById.item collection</summary>
        /// <param name="position">id</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.DeleteDeviceGroupById.Item.DeleteDeviceGroupByIdItemRequestBuilder"/></returns>
        public global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.DeleteDeviceGroupById.Item.DeleteDeviceGroupByIdItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.DeleteDeviceGroupById.Item.DeleteDeviceGroupByIdItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the RIoT.Sdk.Generated.Device.api.device.v1.group.deleteDeviceGroupById.item collection</summary>
        /// <param name="position">id</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.DeleteDeviceGroupById.Item.DeleteDeviceGroupByIdItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.DeleteDeviceGroupById.Item.DeleteDeviceGroupByIdItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.DeleteDeviceGroupById.Item.DeleteDeviceGroupByIdItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.DeleteDeviceGroupById.DeleteDeviceGroupByIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteDeviceGroupByIdRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device/v1/group/deleteDeviceGroupById", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.DeleteDeviceGroupById.DeleteDeviceGroupByIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteDeviceGroupByIdRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device/v1/group/deleteDeviceGroupById", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
