// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.GetVehicleInfo.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.GetVehicleInfo
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\v1\task\getVehicleInfo
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetVehicleInfoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the RIoT.Sdk.Generated.TaskApi.api.task.v1.task.getVehicleInfo.item collection</summary>
        /// <param name="position">deviceKey</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.GetVehicleInfo.Item.WithDeviceKeyItemRequestBuilder"/></returns>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.GetVehicleInfo.Item.WithDeviceKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("deviceKey", position);
                return new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.GetVehicleInfo.Item.WithDeviceKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.GetVehicleInfo.GetVehicleInfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetVehicleInfoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/task/getVehicleInfo", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.GetVehicleInfo.GetVehicleInfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetVehicleInfoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/task/getVehicleInfo", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
