// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Order.CurrentMapExistNotFinalOrderTask.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Order.CurrentMapExistNotFinalOrderTask
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\v1\order\currentMapExistNotFinalOrderTask
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CurrentMapExistNotFinalOrderTaskRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the RIoT.Sdk.Generated.TaskApi.api.task.v1.order.currentMapExistNotFinalOrderTask.item collection</summary>
        /// <param name="position">mapId</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Order.CurrentMapExistNotFinalOrderTask.Item.WithMapItemRequestBuilder"/></returns>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Order.CurrentMapExistNotFinalOrderTask.Item.WithMapItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("mapId", position);
                return new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Order.CurrentMapExistNotFinalOrderTask.Item.WithMapItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the RIoT.Sdk.Generated.TaskApi.api.task.v1.order.currentMapExistNotFinalOrderTask.item collection</summary>
        /// <param name="position">mapId</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Order.CurrentMapExistNotFinalOrderTask.Item.WithMapItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Order.CurrentMapExistNotFinalOrderTask.Item.WithMapItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("mapId", position);
                return new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Order.CurrentMapExistNotFinalOrderTask.Item.WithMapItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Order.CurrentMapExistNotFinalOrderTask.CurrentMapExistNotFinalOrderTaskRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurrentMapExistNotFinalOrderTaskRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/order/currentMapExistNotFinalOrderTask", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Order.CurrentMapExistNotFinalOrderTask.CurrentMapExistNotFinalOrderTaskRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurrentMapExistNotFinalOrderTaskRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/order/currentMapExistNotFinalOrderTask", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
