// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.Setting.Get;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.Setting.Update;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.Setting
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\vehicles\setting
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SettingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getPath property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.Setting.Get.GetRequestBuilder GetPath
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.Setting.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.Setting.Update.UpdateRequestBuilder Update
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.Setting.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.Setting.SettingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SettingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/vehicles/setting", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.Setting.SettingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SettingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/vehicles/setting", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
