// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.ExportSystemlog;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.Page;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.QueryNotRead;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.Read;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.ReadAll;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.Unread;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.UpdateStatus;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\systemLog
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SystemLogRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The exportSystemlog property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.ExportSystemlog.ExportSystemlogRequestBuilder ExportSystemlog
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.ExportSystemlog.ExportSystemlogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The page property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.Page.PageRequestBuilder Page
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.Page.PageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queryNotRead property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.QueryNotRead.QueryNotReadRequestBuilder QueryNotRead
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.QueryNotRead.QueryNotReadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The read property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.Read.ReadRequestBuilder Read
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.Read.ReadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The readAll property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.ReadAll.ReadAllRequestBuilder ReadAll
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.ReadAll.ReadAllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unread property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.Unread.UnreadRequestBuilder Unread
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.Unread.UnreadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateStatus property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.UpdateStatus.UpdateStatusRequestBuilder UpdateStatus
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.UpdateStatus.UpdateStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.SystemLogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemLogRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/systemLog", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.SystemLog.SystemLogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemLogRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/systemLog", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
