// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Imap.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Edge : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cost property</summary>
        public float? Cost { get; set; }
        /// <summary>The cx property</summary>
        public int? Cx { get; set; }
        /// <summary>The cy property</summary>
        public int? Cy { get; set; }
        /// <summary>The desc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Desc { get; set; }
#nullable restore
#else
        public string Desc { get; set; }
#endif
        /// <summary>The direction property</summary>
        public int? Direction { get; set; }
        /// <summary>The dx property</summary>
        public int? Dx { get; set; }
        /// <summary>The dy property</summary>
        public int? Dy { get; set; }
        /// <summary>The efacing property</summary>
        public double? Efacing { get; set; }
        /// <summary>The enode property</summary>
        public int? Enode { get; set; }
        /// <summary>The ex property</summary>
        public int? Ex { get; set; }
        /// <summary>The ey property</summary>
        public int? Ey { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isBackEdge property</summary>
        public bool? IsBackEdge { get; set; }
        /// <summary>The limitV property</summary>
        public int? LimitV { get; set; }
        /// <summary>The limitW property</summary>
        public int? LimitW { get; set; }
        /// <summary>The param property</summary>
        public int? Param { get; set; }
        /// <summary>The radius property</summary>
        public int? Radius { get; set; }
        /// <summary>The robotDirection property</summary>
        public int? RobotDirection { get; set; }
        /// <summary>The rotateDirection property</summary>
        public int? RotateDirection { get; set; }
        /// <summary>The sfacing property</summary>
        public double? Sfacing { get; set; }
        /// <summary>The snode property</summary>
        public int? Snode { get; set; }
        /// <summary>The sx property</summary>
        public int? Sx { get; set; }
        /// <summary>The sy property</summary>
        public int? Sy { get; set; }
        /// <summary>The type property</summary>
        public int? Type { get; set; }
        /// <summary>The userDefinedProperties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.Imap.Models.Edge_userDefinedProperties? UserDefinedProperties { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.Imap.Models.Edge_userDefinedProperties UserDefinedProperties { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Models.Edge"/> and sets the default values.
        /// </summary>
        public Edge()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Models.Edge"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Imap.Models.Edge CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Imap.Models.Edge();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cost", n => { Cost = n.GetFloatValue(); } },
                { "cx", n => { Cx = n.GetIntValue(); } },
                { "cy", n => { Cy = n.GetIntValue(); } },
                { "desc", n => { Desc = n.GetStringValue(); } },
                { "direction", n => { Direction = n.GetIntValue(); } },
                { "dx", n => { Dx = n.GetIntValue(); } },
                { "dy", n => { Dy = n.GetIntValue(); } },
                { "efacing", n => { Efacing = n.GetDoubleValue(); } },
                { "enode", n => { Enode = n.GetIntValue(); } },
                { "ex", n => { Ex = n.GetIntValue(); } },
                { "ey", n => { Ey = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isBackEdge", n => { IsBackEdge = n.GetBoolValue(); } },
                { "limitV", n => { LimitV = n.GetIntValue(); } },
                { "limitW", n => { LimitW = n.GetIntValue(); } },
                { "param", n => { Param = n.GetIntValue(); } },
                { "radius", n => { Radius = n.GetIntValue(); } },
                { "robotDirection", n => { RobotDirection = n.GetIntValue(); } },
                { "rotateDirection", n => { RotateDirection = n.GetIntValue(); } },
                { "sfacing", n => { Sfacing = n.GetDoubleValue(); } },
                { "snode", n => { Snode = n.GetIntValue(); } },
                { "sx", n => { Sx = n.GetIntValue(); } },
                { "sy", n => { Sy = n.GetIntValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
                { "userDefinedProperties", n => { UserDefinedProperties = n.GetObjectValue<global::RIoT.Sdk.Generated.Imap.Models.Edge_userDefinedProperties>(global::RIoT.Sdk.Generated.Imap.Models.Edge_userDefinedProperties.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("cost", Cost);
            writer.WriteIntValue("cx", Cx);
            writer.WriteIntValue("cy", Cy);
            writer.WriteStringValue("desc", Desc);
            writer.WriteIntValue("direction", Direction);
            writer.WriteIntValue("dx", Dx);
            writer.WriteIntValue("dy", Dy);
            writer.WriteDoubleValue("efacing", Efacing);
            writer.WriteIntValue("enode", Enode);
            writer.WriteIntValue("ex", Ex);
            writer.WriteIntValue("ey", Ey);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isBackEdge", IsBackEdge);
            writer.WriteIntValue("limitV", LimitV);
            writer.WriteIntValue("limitW", LimitW);
            writer.WriteIntValue("param", Param);
            writer.WriteIntValue("radius", Radius);
            writer.WriteIntValue("robotDirection", RobotDirection);
            writer.WriteIntValue("rotateDirection", RotateDirection);
            writer.WriteDoubleValue("sfacing", Sfacing);
            writer.WriteIntValue("snode", Snode);
            writer.WriteIntValue("sx", Sx);
            writer.WriteIntValue("sy", Sy);
            writer.WriteIntValue("type", Type);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.Imap.Models.Edge_userDefinedProperties>("userDefinedProperties", UserDefinedProperties);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
