// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.Imap.Models
{
    /// <summary>状态 activated, inactivated</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MapInfoObject_state
    {
        [EnumMember(Value = "activated")]
        #pragma warning disable CS1591
        Activated,
        #pragma warning restore CS1591
        [EnumMember(Value = "inactivated")]
        #pragma warning disable CS1591
        Inactivated,
        #pragma warning restore CS1591
    }
}
