// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Imap.Models
{
    /// <summary>
    /// 地图移除站点表
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MapRemovedStationObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>创建时间</summary>
        public DateTimeOffset? GmtCreate { get; set; }
        /// <summary>更新时间</summary>
        public DateTimeOffset? GmtUpdate { get; set; }
        /// <summary>移除站点记录id</summary>
        public int? Id { get; set; }
        /// <summary>移除站点的地图id</summary>
        public int? MapId { get; set; }
        /// <summary>移除站点id</summary>
        public int? StationId { get; set; }
        /// <summary>移除站点名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationName { get; set; }
#nullable restore
#else
        public string StationName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Models.MapRemovedStationObject"/> and sets the default values.
        /// </summary>
        public MapRemovedStationObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Models.MapRemovedStationObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Imap.Models.MapRemovedStationObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Imap.Models.MapRemovedStationObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gmtCreate", n => { GmtCreate = n.GetDateTimeOffsetValue(); } },
                { "gmtUpdate", n => { GmtUpdate = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "mapId", n => { MapId = n.GetIntValue(); } },
                { "stationId", n => { StationId = n.GetIntValue(); } },
                { "stationName", n => { StationName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("gmtCreate", GmtCreate);
            writer.WriteDateTimeOffsetValue("gmtUpdate", GmtUpdate);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("mapId", MapId);
            writer.WriteIntValue("stationId", StationId);
            writer.WriteStringValue("stationName", StationName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
