// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Imap.Models
{
    /// <summary>
    /// 地图同步记录表
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MapSyncRecordObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>推送记录中的设备列表</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.Imap.Models.DeviceObject>? DeviceList { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.Imap.Models.DeviceObject> DeviceList { get; set; }
#endif
        /// <summary>同步时间</summary>
        public DateTimeOffset? GmtCreate { get; set; }
        /// <summary>更新时间</summary>
        public DateTimeOffset? GmtUpdate { get; set; }
        /// <summary>同步记录id</summary>
        public int? Id { get; set; }
        /// <summary>同步记录地图名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MapName { get; set; }
#nullable restore
#else
        public string MapName { get; set; }
#endif
        /// <summary>同步结果</summary>
        public global::RIoT.Sdk.Generated.Imap.Models.MapSyncRecordObject_mapSyncResult? MapSyncResult { get; set; }
        /// <summary>同步来源</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MapSyncSource { get; set; }
#nullable restore
#else
        public string MapSyncSource { get; set; }
#endif
        /// <summary>同步对象</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MapSyncTarget { get; set; }
#nullable restore
#else
        public string MapSyncTarget { get; set; }
#endif
        /// <summary>同步的类型</summary>
        public global::RIoT.Sdk.Generated.Imap.Models.MapSyncRecordObject_mapSyncType? MapSyncType { get; set; }
        /// <summary>同步备注</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>操作者</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Operator { get; set; }
#nullable restore
#else
        public string Operator { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Models.MapSyncRecordObject"/> and sets the default values.
        /// </summary>
        public MapSyncRecordObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Models.MapSyncRecordObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Imap.Models.MapSyncRecordObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Imap.Models.MapSyncRecordObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "deviceList", n => { DeviceList = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.Imap.Models.DeviceObject>(global::RIoT.Sdk.Generated.Imap.Models.DeviceObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "gmtCreate", n => { GmtCreate = n.GetDateTimeOffsetValue(); } },
                { "gmtUpdate", n => { GmtUpdate = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "mapName", n => { MapName = n.GetStringValue(); } },
                { "mapSyncResult", n => { MapSyncResult = n.GetEnumValue<global::RIoT.Sdk.Generated.Imap.Models.MapSyncRecordObject_mapSyncResult>(); } },
                { "mapSyncSource", n => { MapSyncSource = n.GetStringValue(); } },
                { "mapSyncTarget", n => { MapSyncTarget = n.GetStringValue(); } },
                { "mapSyncType", n => { MapSyncType = n.GetEnumValue<global::RIoT.Sdk.Generated.Imap.Models.MapSyncRecordObject_mapSyncType>(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "operator", n => { Operator = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.Imap.Models.DeviceObject>("deviceList", DeviceList);
            writer.WriteDateTimeOffsetValue("gmtCreate", GmtCreate);
            writer.WriteDateTimeOffsetValue("gmtUpdate", GmtUpdate);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("mapName", MapName);
            writer.WriteEnumValue<global::RIoT.Sdk.Generated.Imap.Models.MapSyncRecordObject_mapSyncResult>("mapSyncResult", MapSyncResult);
            writer.WriteStringValue("mapSyncSource", MapSyncSource);
            writer.WriteStringValue("mapSyncTarget", MapSyncTarget);
            writer.WriteEnumValue<global::RIoT.Sdk.Generated.Imap.Models.MapSyncRecordObject_mapSyncType>("mapSyncType", MapSyncType);
            writer.WriteStringValue("note", Note);
            writer.WriteStringValue("operator", Operator);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
