// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ActionTask : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The no property</summary>
        public int? No { get; set; }
        /// <summary>The param0 property</summary>
        public int? Param0 { get; set; }
        /// <summary>The param1 property</summary>
        public int? Param1 { get; set; }
        /// <summary>The paramStr property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParamStr { get; set; }
#nullable restore
#else
        public string ParamStr { get; set; }
#endif
        /// <summary>The result property</summary>
        public int? Result { get; set; }
        /// <summary>The resultCode property</summary>
        public int? ResultCode { get; set; }
        /// <summary>The resultStr property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultStr { get; set; }
#nullable restore
#else
        public string ResultStr { get; set; }
#endif
        /// <summary>The state property</summary>
        public int? State { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.ActionTask"/> and sets the default values.
        /// </summary>
        public ActionTask()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.ActionTask"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.TaskApi.Models.ActionTask CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.TaskApi.Models.ActionTask();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetIntValue(); } },
                { "no", n => { No = n.GetIntValue(); } },
                { "param0", n => { Param0 = n.GetIntValue(); } },
                { "param1", n => { Param1 = n.GetIntValue(); } },
                { "paramStr", n => { ParamStr = n.GetStringValue(); } },
                { "result", n => { Result = n.GetIntValue(); } },
                { "resultCode", n => { ResultCode = n.GetIntValue(); } },
                { "resultStr", n => { ResultStr = n.GetStringValue(); } },
                { "state", n => { State = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("no", No);
            writer.WriteIntValue("param0", Param0);
            writer.WriteIntValue("param1", Param1);
            writer.WriteStringValue("paramStr", ParamStr);
            writer.WriteIntValue("result", Result);
            writer.WriteIntValue("resultCode", ResultCode);
            writer.WriteStringValue("resultStr", ResultStr);
            writer.WriteIntValue("state", State);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
