// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgvLogDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The logs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.TaskApi.Models.AgvLog>? Logs { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.TaskApi.Models.AgvLog> Logs { get; set; }
#endif
        /// <summary>The modules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.TaskApi.Models.Modules? Modules { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.TaskApi.Models.Modules Modules { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.AgvLogDto"/> and sets the default values.
        /// </summary>
        public AgvLogDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.AgvLogDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.TaskApi.Models.AgvLogDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.TaskApi.Models.AgvLogDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "logs", n => { Logs = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.TaskApi.Models.AgvLog>(global::RIoT.Sdk.Generated.TaskApi.Models.AgvLog.CreateFromDiscriminatorValue)?.AsList(); } },
                { "modules", n => { Modules = n.GetObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.Modules>(global::RIoT.Sdk.Generated.TaskApi.Models.Modules.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.TaskApi.Models.AgvLog>("logs", Logs);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.Modules>("modules", Modules);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
