// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CheckFailDetail : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The appliedVehicleId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppliedVehicleId { get; set; }
#nullable restore
#else
        public string AppliedVehicleId { get; set; }
#endif
        /// <summary>The detail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Detail { get; set; }
#nullable restore
#else
        public string Detail { get; set; }
#endif
        /// <summary>The lockedVehicleIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? LockedVehicleIds { get; set; }
#nullable restore
#else
        public List<string> LockedVehicleIds { get; set; }
#endif
        /// <summary>The time property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Time { get; set; }
#nullable restore
#else
        public string Time { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Models.CheckFailDetail_type? Type { get; set; }
        /// <summary>The vehicleNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? VehicleNames { get; set; }
#nullable restore
#else
        public List<string> VehicleNames { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.CheckFailDetail"/> and sets the default values.
        /// </summary>
        public CheckFailDetail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.CheckFailDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.TaskApi.Models.CheckFailDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.TaskApi.Models.CheckFailDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "appliedVehicleId", n => { AppliedVehicleId = n.GetStringValue(); } },
                { "detail", n => { Detail = n.GetStringValue(); } },
                { "lockedVehicleIds", n => { LockedVehicleIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "time", n => { Time = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::RIoT.Sdk.Generated.TaskApi.Models.CheckFailDetail_type>(); } },
                { "vehicleNames", n => { VehicleNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("appliedVehicleId", AppliedVehicleId);
            writer.WriteStringValue("detail", Detail);
            writer.WriteCollectionOfPrimitiveValues<string>("lockedVehicleIds", LockedVehicleIds);
            writer.WriteStringValue("time", Time);
            writer.WriteEnumValue<global::RIoT.Sdk.Generated.TaskApi.Models.CheckFailDetail_type>("type", Type);
            writer.WriteCollectionOfPrimitiveValues<string>("vehicleNames", VehicleNames);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
