// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HardwareState : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The batteryCurrent property</summary>
        public int? BatteryCurrent { get; set; }
        /// <summary>The batteryPercentage property</summary>
        public int? BatteryPercentage { get; set; }
        /// <summary>The batteryState property</summary>
        public int? BatteryState { get; set; }
        /// <summary>The batteryTemperature property</summary>
        public int? BatteryTemperature { get; set; }
        /// <summary>The batteryUseCycles property</summary>
        public int? BatteryUseCycles { get; set; }
        /// <summary>The batteryVoltage property</summary>
        public int? BatteryVoltage { get; set; }
        /// <summary>The boxTemperature property</summary>
        public int? BoxTemperature { get; set; }
        /// <summary>The breakSwState property</summary>
        public int? BreakSwState { get; set; }
        /// <summary>The cpuTemperature property</summary>
        public int? CpuTemperature { get; set; }
        /// <summary>The cpuUsage property</summary>
        public int? CpuUsage { get; set; }
        /// <summary>The desc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Desc { get; set; }
#nullable restore
#else
        public string Desc { get; set; }
#endif
        /// <summary>The deviceId property</summary>
        public long? DeviceId { get; set; }
        /// <summary>The diskUsage property</summary>
        public int? DiskUsage { get; set; }
        /// <summary>The hardwareErrorCode property</summary>
        public int? HardwareErrorCode { get; set; }
        /// <summary>The hostPort property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HostPort { get; set; }
#nullable restore
#else
        public string HostPort { get; set; }
#endif
        /// <summary>The hstate property</summary>
        public int? Hstate { get; set; }
        /// <summary>The m1StatusCode property</summary>
        public int? M1StatusCode { get; set; }
        /// <summary>The m2StatusCode property</summary>
        public int? M2StatusCode { get; set; }
        /// <summary>The m3StatusCode property</summary>
        public int? M3StatusCode { get; set; }
        /// <summary>The m4StatusCode property</summary>
        public int? M4StatusCode { get; set; }
        /// <summary>The memoryUsage property</summary>
        public int? MemoryUsage { get; set; }
        /// <summary>The modelVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModelVersion { get; set; }
#nullable restore
#else
        public string ModelVersion { get; set; }
#endif
        /// <summary>The nodeType property</summary>
        public int? NodeType { get; set; }
        /// <summary>The powerState property</summary>
        public int? PowerState { get; set; }
        /// <summary>The remainDiskSpace property</summary>
        public int? RemainDiskSpace { get; set; }
        /// <summary>The totalMileage property</summary>
        public int? TotalMileage { get; set; }
        /// <summary>The totalPowerCycle property</summary>
        public int? TotalPowerCycle { get; set; }
        /// <summary>The totalPoweronTime property</summary>
        public int? TotalPoweronTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.HardwareState"/> and sets the default values.
        /// </summary>
        public HardwareState()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.HardwareState"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.TaskApi.Models.HardwareState CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.TaskApi.Models.HardwareState();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batteryCurrent", n => { BatteryCurrent = n.GetIntValue(); } },
                { "batteryPercentage", n => { BatteryPercentage = n.GetIntValue(); } },
                { "batteryState", n => { BatteryState = n.GetIntValue(); } },
                { "batteryTemperature", n => { BatteryTemperature = n.GetIntValue(); } },
                { "batteryUseCycles", n => { BatteryUseCycles = n.GetIntValue(); } },
                { "batteryVoltage", n => { BatteryVoltage = n.GetIntValue(); } },
                { "boxTemperature", n => { BoxTemperature = n.GetIntValue(); } },
                { "breakSwState", n => { BreakSwState = n.GetIntValue(); } },
                { "cpuTemperature", n => { CpuTemperature = n.GetIntValue(); } },
                { "cpuUsage", n => { CpuUsage = n.GetIntValue(); } },
                { "desc", n => { Desc = n.GetStringValue(); } },
                { "deviceId", n => { DeviceId = n.GetLongValue(); } },
                { "diskUsage", n => { DiskUsage = n.GetIntValue(); } },
                { "hardwareErrorCode", n => { HardwareErrorCode = n.GetIntValue(); } },
                { "hostPort", n => { HostPort = n.GetStringValue(); } },
                { "hstate", n => { Hstate = n.GetIntValue(); } },
                { "m1StatusCode", n => { M1StatusCode = n.GetIntValue(); } },
                { "m2StatusCode", n => { M2StatusCode = n.GetIntValue(); } },
                { "m3StatusCode", n => { M3StatusCode = n.GetIntValue(); } },
                { "m4StatusCode", n => { M4StatusCode = n.GetIntValue(); } },
                { "memoryUsage", n => { MemoryUsage = n.GetIntValue(); } },
                { "modelVersion", n => { ModelVersion = n.GetStringValue(); } },
                { "nodeType", n => { NodeType = n.GetIntValue(); } },
                { "powerState", n => { PowerState = n.GetIntValue(); } },
                { "remainDiskSpace", n => { RemainDiskSpace = n.GetIntValue(); } },
                { "totalMileage", n => { TotalMileage = n.GetIntValue(); } },
                { "totalPowerCycle", n => { TotalPowerCycle = n.GetIntValue(); } },
                { "totalPoweronTime", n => { TotalPoweronTime = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("batteryCurrent", BatteryCurrent);
            writer.WriteIntValue("batteryPercentage", BatteryPercentage);
            writer.WriteIntValue("batteryState", BatteryState);
            writer.WriteIntValue("batteryTemperature", BatteryTemperature);
            writer.WriteIntValue("batteryUseCycles", BatteryUseCycles);
            writer.WriteIntValue("batteryVoltage", BatteryVoltage);
            writer.WriteIntValue("boxTemperature", BoxTemperature);
            writer.WriteIntValue("breakSwState", BreakSwState);
            writer.WriteIntValue("cpuTemperature", CpuTemperature);
            writer.WriteIntValue("cpuUsage", CpuUsage);
            writer.WriteStringValue("desc", Desc);
            writer.WriteLongValue("deviceId", DeviceId);
            writer.WriteIntValue("diskUsage", DiskUsage);
            writer.WriteIntValue("hardwareErrorCode", HardwareErrorCode);
            writer.WriteStringValue("hostPort", HostPort);
            writer.WriteIntValue("hstate", Hstate);
            writer.WriteIntValue("m1StatusCode", M1StatusCode);
            writer.WriteIntValue("m2StatusCode", M2StatusCode);
            writer.WriteIntValue("m3StatusCode", M3StatusCode);
            writer.WriteIntValue("m4StatusCode", M4StatusCode);
            writer.WriteIntValue("memoryUsage", MemoryUsage);
            writer.WriteStringValue("modelVersion", ModelVersion);
            writer.WriteIntValue("nodeType", NodeType);
            writer.WriteIntValue("powerState", PowerState);
            writer.WriteIntValue("remainDiskSpace", RemainDiskSpace);
            writer.WriteIntValue("totalMileage", TotalMileage);
            writer.WriteIntValue("totalPowerCycle", TotalPowerCycle);
            writer.WriteIntValue("totalPoweronTime", TotalPoweronTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
