// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MissionDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The actionId property</summary>
        public int? ActionId { get; set; }
        /// <summary>The actionName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionName { get; set; }
#nullable restore
#else
        public string ActionName { get; set; }
#endif
        /// <summary>The actionParam1 property</summary>
        public int? ActionParam1 { get; set; }
        /// <summary>The actionParam2 property</summary>
        public int? ActionParam2 { get; set; }
        /// <summary>The actionParamStr property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionParamStr { get; set; }
#nullable restore
#else
        public string ActionParamStr { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The destination property</summary>
        public int? Destination { get; set; }
        /// <summary>The extendParams property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.TaskApi.Models.MissionDTO_extendParams? ExtendParams { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.TaskApi.Models.MissionDTO_extendParams ExtendParams { get; set; }
#endif
        /// <summary>The failStrategy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailStrategy { get; set; }
#nullable restore
#else
        public string FailStrategy { get; set; }
#endif
        /// <summary>The failValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailValue { get; set; }
#nullable restore
#else
        public string FailValue { get; set; }
#endif
        /// <summary>The functionKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FunctionKey { get; set; }
#nullable restore
#else
        public string FunctionKey { get; set; }
#endif
        /// <summary>The index property</summary>
        public int? Index { get; set; }
        /// <summary>The length property</summary>
        public int? Length { get; set; }
        /// <summary>The mapId property</summary>
        public int? MapId { get; set; }
        /// <summary>The mapName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MapName { get; set; }
#nullable restore
#else
        public string MapName { get; set; }
#endif
        /// <summary>The orderId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderId { get; set; }
#nullable restore
#else
        public string OrderId { get; set; }
#endif
        /// <summary>The orderUuid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderUuid { get; set; }
#nullable restore
#else
        public string OrderUuid { get; set; }
#endif
        /// <summary>The speed property</summary>
        public float? Speed { get; set; }
        /// <summary>The stationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationName { get; set; }
#nullable restore
#else
        public string StationName { get; set; }
#endif
        /// <summary>The successStrategy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SuccessStrategy { get; set; }
#nullable restore
#else
        public string SuccessStrategy { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The width property</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.MissionDTO"/> and sets the default values.
        /// </summary>
        public MissionDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.MissionDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.TaskApi.Models.MissionDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.TaskApi.Models.MissionDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actionId", n => { ActionId = n.GetIntValue(); } },
                { "actionName", n => { ActionName = n.GetStringValue(); } },
                { "actionParam1", n => { ActionParam1 = n.GetIntValue(); } },
                { "actionParam2", n => { ActionParam2 = n.GetIntValue(); } },
                { "actionParamStr", n => { ActionParamStr = n.GetStringValue(); } },
                { "destination", n => { Destination = n.GetIntValue(); } },
                { "extendParams", n => { ExtendParams = n.GetObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.MissionDTO_extendParams>(global::RIoT.Sdk.Generated.TaskApi.Models.MissionDTO_extendParams.CreateFromDiscriminatorValue); } },
                { "failStrategy", n => { FailStrategy = n.GetStringValue(); } },
                { "failValue", n => { FailValue = n.GetStringValue(); } },
                { "functionKey", n => { FunctionKey = n.GetStringValue(); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "length", n => { Length = n.GetIntValue(); } },
                { "mapId", n => { MapId = n.GetIntValue(); } },
                { "mapName", n => { MapName = n.GetStringValue(); } },
                { "orderId", n => { OrderId = n.GetStringValue(); } },
                { "orderUuid", n => { OrderUuid = n.GetStringValue(); } },
                { "speed", n => { Speed = n.GetFloatValue(); } },
                { "stationName", n => { StationName = n.GetStringValue(); } },
                { "successStrategy", n => { SuccessStrategy = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("actionId", ActionId);
            writer.WriteStringValue("actionName", ActionName);
            writer.WriteIntValue("actionParam1", ActionParam1);
            writer.WriteIntValue("actionParam2", ActionParam2);
            writer.WriteStringValue("actionParamStr", ActionParamStr);
            writer.WriteIntValue("destination", Destination);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.MissionDTO_extendParams>("extendParams", ExtendParams);
            writer.WriteStringValue("failStrategy", FailStrategy);
            writer.WriteStringValue("failValue", FailValue);
            writer.WriteStringValue("functionKey", FunctionKey);
            writer.WriteIntValue("index", Index);
            writer.WriteIntValue("length", Length);
            writer.WriteIntValue("mapId", MapId);
            writer.WriteStringValue("mapName", MapName);
            writer.WriteStringValue("orderId", OrderId);
            writer.WriteStringValue("orderUuid", OrderUuid);
            writer.WriteFloatValue("speed", Speed);
            writer.WriteStringValue("stationName", StationName);
            writer.WriteStringValue("successStrategy", SuccessStrategy);
            writer.WriteStringValue("type", Type);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
