// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    /// <summary>订单操作类型</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderCommandDTOObject_commandType
    {
        [EnumMember(Value = "CMD_ORDER_CANCEL")]
        #pragma warning disable CS1591
        CMD_ORDER_CANCEL,
        #pragma warning restore CS1591
        [EnumMember(Value = "CMD_ORDER_CONTINUE_FROM_HANG")]
        #pragma warning disable CS1591
        CMD_ORDER_CONTINUE_FROM_HANG,
        #pragma warning restore CS1591
        [EnumMember(Value = "CMD_ORDER_CONTINUE_FROM_HELD")]
        #pragma warning disable CS1591
        CMD_ORDER_CONTINUE_FROM_HELD,
        #pragma warning restore CS1591
        [EnumMember(Value = "CMD_ORDER_CONTINUE_FROM_REJECTED")]
        #pragma warning disable CS1591
        CMD_ORDER_CONTINUE_FROM_REJECTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CMD_ORDER_HELD")]
        #pragma warning disable CS1591
        CMD_ORDER_HELD,
        #pragma warning restore CS1591
        [EnumMember(Value = "CMD_ORDER_JUMP_FROM_HANG")]
        #pragma warning disable CS1591
        CMD_ORDER_JUMP_FROM_HANG,
        #pragma warning restore CS1591
        [EnumMember(Value = "CMD_ORDER_REJECTED")]
        #pragma warning disable CS1591
        CMD_ORDER_REJECTED,
        #pragma warning restore CS1591
    }
}
