// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SystemLogStatusDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The deadly property</summary>
        public long? Deadly { get; set; }
        /// <summary>The deadlyList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogObject>? DeadlyList { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogObject> DeadlyList { get; set; }
#endif
        /// <summary>The error property</summary>
        public long? Error { get; set; }
        /// <summary>The normal property</summary>
        public long? Normal { get; set; }
        /// <summary>The total property</summary>
        public long? Total { get; set; }
        /// <summary>The warmList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogObject>? WarmList { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogObject> WarmList { get; set; }
#endif
        /// <summary>The warn property</summary>
        public long? Warn { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogStatusDTO"/> and sets the default values.
        /// </summary>
        public SystemLogStatusDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogStatusDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogStatusDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogStatusDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "deadly", n => { Deadly = n.GetLongValue(); } },
                { "deadlyList", n => { DeadlyList = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogObject>(global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "error", n => { Error = n.GetLongValue(); } },
                { "normal", n => { Normal = n.GetLongValue(); } },
                { "total", n => { Total = n.GetLongValue(); } },
                { "warmList", n => { WarmList = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogObject>(global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "warn", n => { Warn = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("deadly", Deadly);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogObject>("deadlyList", DeadlyList);
            writer.WriteLongValue("error", Error);
            writer.WriteLongValue("normal", Normal);
            writer.WriteLongValue("total", Total);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.TaskApi.Models.SystemLogObject>("warmList", WarmList);
            writer.WriteLongValue("warn", Warn);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
