// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    /// <summary>
    /// 充电桩电量统计
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class U5145u7535u6869u7535u91cfu7edfu8ba1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>平均充电次数</summary>
        public float? AvgChargeLocationCount { get; set; }
        /// <summary>平均充电时长</summary>
        public float? AvgChargeLocationTime { get; set; }
        /// <summary>充电桩数据集合</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.TaskApi.Models.U5145u7535u6869u6570u636e>? ChargeLocationStatisticsHistograms { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.TaskApi.Models.U5145u7535u6869u6570u636e> ChargeLocationStatisticsHistograms { get; set; }
#endif
        /// <summary>总充电次数</summary>
        public float? TotalChargeLocationCount { get; set; }
        /// <summary>总充电时长</summary>
        public float? TotalChargeLocationTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.U5145u7535u6869u7535u91cfu7edfu8ba1"/> and sets the default values.
        /// </summary>
        public U5145u7535u6869u7535u91cfu7edfu8ba1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.U5145u7535u6869u7535u91cfu7edfu8ba1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.TaskApi.Models.U5145u7535u6869u7535u91cfu7edfu8ba1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.TaskApi.Models.U5145u7535u6869u7535u91cfu7edfu8ba1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avgChargeLocationCount", n => { AvgChargeLocationCount = n.GetFloatValue(); } },
                { "avgChargeLocationTime", n => { AvgChargeLocationTime = n.GetFloatValue(); } },
                { "chargeLocationStatisticsHistograms", n => { ChargeLocationStatisticsHistograms = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.TaskApi.Models.U5145u7535u6869u6570u636e>(global::RIoT.Sdk.Generated.TaskApi.Models.U5145u7535u6869u6570u636e.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalChargeLocationCount", n => { TotalChargeLocationCount = n.GetFloatValue(); } },
                { "totalChargeLocationTime", n => { TotalChargeLocationTime = n.GetFloatValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("avgChargeLocationCount", AvgChargeLocationCount);
            writer.WriteFloatValue("avgChargeLocationTime", AvgChargeLocationTime);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.TaskApi.Models.U5145u7535u6869u6570u636e>("chargeLocationStatisticsHistograms", ChargeLocationStatisticsHistograms);
            writer.WriteFloatValue("totalChargeLocationCount", TotalChargeLocationCount);
            writer.WriteFloatValue("totalChargeLocationTime", TotalChargeLocationTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
