// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    /// <summary>文件类型</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum U8f66u8f86u6587u4ef6u540du79f0_type
    {
        [EnumMember(Value = "SRC_UPGRADE")]
        #pragma warning disable CS1591
        SRC_UPGRADE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SROS_UPGRADE")]
        #pragma warning disable CS1591
        SROS_UPGRADE,
        #pragma warning restore CS1591
    }
}
