// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    /// <summary>
    /// 车辆升级列表查询请求对象
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class U8f66u8f86u5347u7ea7u5217u8868u67e5u8be2u8bf7u6c42Object : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>车辆组id集合</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? GroupIds { get; set; }
#nullable restore
#else
        public List<long?> GroupIds { get; set; }
#endif
        /// <summary>页码</summary>
        public int? PageNum { get; set; }
        /// <summary>页尺寸(page:1,size:-1查询所有)</summary>
        public int? PageSize { get; set; }
        /// <summary>车辆条件对象</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.TaskApi.Models.U8f66u8f86u6761u4ef6Object? QueryDeviceDto { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.TaskApi.Models.U8f66u8f86u6761u4ef6Object QueryDeviceDto { get; set; }
#endif
        /// <summary>任务类型(SROS_SYNC，SRC_SYNC)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.U8f66u8f86u5347u7ea7u5217u8868u67e5u8be2u8bf7u6c42Object"/> and sets the default values.
        /// </summary>
        public U8f66u8f86u5347u7ea7u5217u8868u67e5u8be2u8bf7u6c42Object()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.U8f66u8f86u5347u7ea7u5217u8868u67e5u8be2u8bf7u6c42Object"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.TaskApi.Models.U8f66u8f86u5347u7ea7u5217u8868u67e5u8be2u8bf7u6c42Object CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.TaskApi.Models.U8f66u8f86u5347u7ea7u5217u8868u67e5u8be2u8bf7u6c42Object();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "groupIds", n => { GroupIds = n.GetCollectionOfPrimitiveValues<long?>()?.AsList(); } },
                { "pageNum", n => { PageNum = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "queryDeviceDto", n => { QueryDeviceDto = n.GetObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.U8f66u8f86u6761u4ef6Object>(global::RIoT.Sdk.Generated.TaskApi.Models.U8f66u8f86u6761u4ef6Object.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<long?>("groupIds", GroupIds);
            writer.WriteIntValue("pageNum", PageNum);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.U8f66u8f86u6761u4ef6Object>("queryDeviceDto", QueryDeviceDto);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
