// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    /// <summary>任务类型</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum U8f66u8f86u540cu6b65u4efbu52a1_type
    {
        [EnumMember(Value = "SRC_SYNC")]
        #pragma warning disable CS1591
        SRC_SYNC,
        #pragma warning restore CS1591
        [EnumMember(Value = "SROS_SYNC")]
        #pragma warning disable CS1591
        SROS_SYNC,
        #pragma warning restore CS1591
    }
}
