// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Vehicle_actionState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "AT_FINISHED")]
        #pragma warning disable CS1591
        AT_FINISHED,
        #pragma warning restore CS1591
        [EnumMember(Value = "AT_IN_CANCEL")]
        #pragma warning disable CS1591
        AT_IN_CANCEL,
        #pragma warning restore CS1591
        [EnumMember(Value = "AT_NA")]
        #pragma warning disable CS1591
        AT_NA,
        #pragma warning restore CS1591
        [EnumMember(Value = "AT_PAUSED")]
        #pragma warning disable CS1591
        AT_PAUSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "AT_RUNNING")]
        #pragma warning disable CS1591
        AT_RUNNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "AT_WAIT_FOR_ACK")]
        #pragma warning disable CS1591
        AT_WAIT_FOR_ACK,
        #pragma warning restore CS1591
        [EnumMember(Value = "AT_WAIT_FOR_START")]
        #pragma warning disable CS1591
        AT_WAIT_FOR_START,
        #pragma warning restore CS1591
    }
}
