// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Vehicle_fleetMode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "FLEET_MODE_NONE")]
        #pragma warning disable CS1591
        FLEET_MODE_NONE,
        #pragma warning restore CS1591
        [EnumMember(Value = "FLEET_MODE_OFFLINE")]
        #pragma warning disable CS1591
        FLEET_MODE_OFFLINE,
        #pragma warning restore CS1591
        [EnumMember(Value = "FLEET_MODE_ONLINE")]
        #pragma warning disable CS1591
        FLEET_MODE_ONLINE,
        #pragma warning restore CS1591
    }
}
