// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VehicleTaskInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The batteryMaintenanceTime property</summary>
        public long? BatteryMaintenanceTime { get; set; }
        /// <summary>The enable property</summary>
        public bool? Enable { get; set; }
        /// <summary>The handlePauseTime property</summary>
        public long? HandlePauseTime { get; set; }
        /// <summary>The integrationLevel property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Models.VehicleTaskInfo_integrationLevel? IntegrationLevel { get; set; }
        /// <summary>The integrationLevelTime property</summary>
        public long? IntegrationLevelTime { get; set; }
        /// <summary>The key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The lastExecuteOrderTimestamp property</summary>
        public long? LastExecuteOrderTimestamp { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The orderSequence property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_OrderSequence? OrderSequence { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_OrderSequence OrderSequence { get; set; }
#endif
        /// <summary>The orderTask property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_OrderTask? OrderTask { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_OrderTask OrderTask { get; set; }
#endif
        /// <summary>The processingOrder property</summary>
        public bool? ProcessingOrder { get; set; }
        /// <summary>The procState property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Models.VehicleTaskInfo_procState? ProcState { get; set; }
        /// <summary>The reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>The reference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_VehicleTaskInfo? Reference { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_VehicleTaskInfo Reference { get; set; }
#endif
        /// <summary>The routeProgressIndex property</summary>
        public int? RouteProgressIndex { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.VehicleTaskInfo"/> and sets the default values.
        /// </summary>
        public VehicleTaskInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.VehicleTaskInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.TaskApi.Models.VehicleTaskInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.TaskApi.Models.VehicleTaskInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batteryMaintenanceTime", n => { BatteryMaintenanceTime = n.GetLongValue(); } },
                { "enable", n => { Enable = n.GetBoolValue(); } },
                { "handlePauseTime", n => { HandlePauseTime = n.GetLongValue(); } },
                { "integrationLevel", n => { IntegrationLevel = n.GetEnumValue<global::RIoT.Sdk.Generated.TaskApi.Models.VehicleTaskInfo_integrationLevel>(); } },
                { "integrationLevelTime", n => { IntegrationLevelTime = n.GetLongValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "lastExecuteOrderTimestamp", n => { LastExecuteOrderTimestamp = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "orderSequence", n => { OrderSequence = n.GetObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_OrderSequence>(global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_OrderSequence.CreateFromDiscriminatorValue); } },
                { "orderTask", n => { OrderTask = n.GetObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_OrderTask>(global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_OrderTask.CreateFromDiscriminatorValue); } },
                { "procState", n => { ProcState = n.GetEnumValue<global::RIoT.Sdk.Generated.TaskApi.Models.VehicleTaskInfo_procState>(); } },
                { "processingOrder", n => { ProcessingOrder = n.GetBoolValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "reference", n => { Reference = n.GetObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_VehicleTaskInfo>(global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_VehicleTaskInfo.CreateFromDiscriminatorValue); } },
                { "routeProgressIndex", n => { RouteProgressIndex = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("batteryMaintenanceTime", BatteryMaintenanceTime);
            writer.WriteBoolValue("enable", Enable);
            writer.WriteLongValue("handlePauseTime", HandlePauseTime);
            writer.WriteEnumValue<global::RIoT.Sdk.Generated.TaskApi.Models.VehicleTaskInfo_integrationLevel>("integrationLevel", IntegrationLevel);
            writer.WriteLongValue("integrationLevelTime", IntegrationLevelTime);
            writer.WriteStringValue("key", Key);
            writer.WriteLongValue("lastExecuteOrderTimestamp", LastExecuteOrderTimestamp);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_OrderSequence>("orderSequence", OrderSequence);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_OrderTask>("orderTask", OrderTask);
            writer.WriteBoolValue("processingOrder", ProcessingOrder);
            writer.WriteEnumValue<global::RIoT.Sdk.Generated.TaskApi.Models.VehicleTaskInfo_procState>("procState", ProcState);
            writer.WriteStringValue("reason", Reason);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.TaskApi.Models.SRObjectReference_Of_VehicleTaskInfo>("reference", Reference);
            writer.WriteIntValue("routeProgressIndex", RouteProgressIndex);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
