// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Vehicle_emergencyState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CAN_NOT_RECOVER")]
        #pragma warning disable CS1591
        CAN_NOT_RECOVER,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAN_RECOVER")]
        #pragma warning disable CS1591
        CAN_RECOVER,
        #pragma warning restore CS1591
        [EnumMember(Value = "OK")]
        #pragma warning disable CS1591
        OK,
        #pragma warning restore CS1591
    }
}
