// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Vehicle_movementState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "MT_FINISHED")]
        #pragma warning disable CS1591
        MT_FINISHED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT_IN_CANCEL")]
        #pragma warning disable CS1591
        MT_IN_CANCEL,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT_NA")]
        #pragma warning disable CS1591
        MT_NA,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT_PAUSED")]
        #pragma warning disable CS1591
        MT_PAUSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT_PAUSED_OBSTACLE")]
        #pragma warning disable CS1591
        MT_PAUSED_OBSTACLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT_PAUSED_OBSTACLE_NO_MORE")]
        #pragma warning disable CS1591
        MT_PAUSED_OBSTACLE_NO_MORE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT_RUNNING")]
        #pragma warning disable CS1591
        MT_RUNNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT_WAIT_FOR_ACK")]
        #pragma warning disable CS1591
        MT_WAIT_FOR_ACK,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT_WAIT_FOR_CHECKPOINT")]
        #pragma warning disable CS1591
        MT_WAIT_FOR_CHECKPOINT,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT_WAIT_FOR_START")]
        #pragma warning disable CS1591
        MT_WAIT_FOR_START,
        #pragma warning restore CS1591
    }
}
