// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Route.CurRemainCost.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Route.CurRemainCost
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\v1\route\curRemainCost
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CurRemainCostRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the RIoT.Sdk.Generated.TaskApi.api.task.v1.route.curRemainCost.item collection</summary>
        /// <param name="position">orderKey</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Route.CurRemainCost.Item.WithOrderKeyItemRequestBuilder"/></returns>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Route.CurRemainCost.Item.WithOrderKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("orderKey", position);
                return new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Route.CurRemainCost.Item.WithOrderKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Route.CurRemainCost.CurRemainCostRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurRemainCostRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/route/curRemainCost", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Route.CurRemainCost.CurRemainCostRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurRemainCostRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/route/curRemainCost", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
