// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.All;
using RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation
{
    /// <summary>
    /// Builds and executes requests for operations under \api\imap\v1\mapRelation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MapRelationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.All.AllRequestBuilder All
        {
            get => new global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EmptyPathSegment property</summary>
        public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the RIoT.Sdk.Generated.Imap.api.imap.v1.mapRelation.item collection</summary>
        /// <param name="position">删除关系id</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.Item.MapRelationItemRequestBuilder"/></returns>
        public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.Item.MapRelationItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.Item.MapRelationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the RIoT.Sdk.Generated.Imap.api.imap.v1.mapRelation.item collection</summary>
        /// <param name="position">删除关系id</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.Item.MapRelationItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.Item.MapRelationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.Item.MapRelationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.MapRelationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MapRelationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imap/v1/mapRelation", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapRelation.MapRelationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MapRelationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imap/v1/mapRelation", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
