// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Order.Models
{
    /// <summary>
    /// 添加订单－根据动态模板生成订单
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DynamicTemplateDTOObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>动态模板</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.Order.Models.DynamicOrderMissionDTO>? DynamicOrderMission { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.Order.Models.DynamicOrderMissionDTO> DynamicOrderMission { get; set; }
#endif
        /// <summary>是否锁定车辆:1.锁定,0.解锁</summary>
        public int? LockStatus { get; set; }
        /// <summary>锁定车辆的key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LockVehicleKey { get; set; }
#nullable restore
#else
        public string LockVehicleKey { get; set; }
#endif
        /// <summary>订单来源 1 FMS, 2 WMS, 3 CALLS, 4 UI</summary>
        public int? Source { get; set; }
        /// <summary>模板id</summary>
        public int? TemplateOrderId { get; set; }
        /// <summary>上层系统订单唯一ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpperId { get; set; }
#nullable restore
#else
        public string UpperId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Models.DynamicTemplateDTOObject"/> and sets the default values.
        /// </summary>
        public DynamicTemplateDTOObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Models.DynamicTemplateDTOObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Order.Models.DynamicTemplateDTOObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Order.Models.DynamicTemplateDTOObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dynamicOrderMission", n => { DynamicOrderMission = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.Order.Models.DynamicOrderMissionDTO>(global::RIoT.Sdk.Generated.Order.Models.DynamicOrderMissionDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lockStatus", n => { LockStatus = n.GetIntValue(); } },
                { "lockVehicleKey", n => { LockVehicleKey = n.GetStringValue(); } },
                { "source", n => { Source = n.GetIntValue(); } },
                { "templateOrderId", n => { TemplateOrderId = n.GetIntValue(); } },
                { "upperId", n => { UpperId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.Order.Models.DynamicOrderMissionDTO>("dynamicOrderMission", DynamicOrderMission);
            writer.WriteIntValue("lockStatus", LockStatus);
            writer.WriteStringValue("lockVehicleKey", LockVehicleKey);
            writer.WriteIntValue("source", Source);
            writer.WriteIntValue("templateOrderId", TemplateOrderId);
            writer.WriteStringValue("upperId", UpperId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
