// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Order.Models
{
    /// <summary>
    /// 订单组合关系表
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrderGroupObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>预约指定执行时间</summary>
        public DateTimeOffset? AppointExecuteTime { get; set; }
        /// <summary>预约指定车型组id</summary>
        public int? AppointVehicleGroupId { get; set; }
        /// <summary>预约指定车辆id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppointVehicleKey { get; set; }
#nullable restore
#else
        public string AppointVehicleKey { get; set; }
#endif
        /// <summary>创建用户</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>创建时间</summary>
        public DateTimeOffset? GmtCreate { get; set; }
        /// <summary>最后更新时间</summary>
        public DateTimeOffset? GmtModified { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>是否支持预约</summary>
        public int? IsAppointEnable { get; set; }
        /// <summary>The isDeleted property</summary>
        public int? IsDeleted { get; set; }
        /// <summary>编辑用户</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModifiedBy { get; set; }
#nullable restore
#else
        public string ModifiedBy { get; set; }
#endif
        /// <summary>订单组合名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderGroupName { get; set; }
#nullable restore
#else
        public string OrderGroupName { get; set; }
#endif
        /// <summary>原始的订单模板id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalTemplateOrderId { get; set; }
#nullable restore
#else
        public string OriginalTemplateOrderId { get; set; }
#endif
        /// <summary>订单组合优先级:0:低优先级,1:中优先级,2:高优先级,3:最高优先级</summary>
        public int? Priority { get; set; }
        /// <summary>订单模板Id集合</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? TemplateOrderIds { get; set; }
#nullable restore
#else
        public List<int?> TemplateOrderIds { get; set; }
#endif
        /// <summary>订单模板map</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.Order.Models.OrderGroupObject_templateOrderMaps? TemplateOrderMaps { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.Order.Models.OrderGroupObject_templateOrderMaps TemplateOrderMaps { get; set; }
#endif
        /// <summary>创建用户</summary>
        public int? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Models.OrderGroupObject"/> and sets the default values.
        /// </summary>
        public OrderGroupObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Models.OrderGroupObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Order.Models.OrderGroupObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Order.Models.OrderGroupObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "appointExecuteTime", n => { AppointExecuteTime = n.GetDateTimeOffsetValue(); } },
                { "appointVehicleGroupId", n => { AppointVehicleGroupId = n.GetIntValue(); } },
                { "appointVehicleKey", n => { AppointVehicleKey = n.GetStringValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "gmtCreate", n => { GmtCreate = n.GetDateTimeOffsetValue(); } },
                { "gmtModified", n => { GmtModified = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isAppointEnable", n => { IsAppointEnable = n.GetIntValue(); } },
                { "isDeleted", n => { IsDeleted = n.GetIntValue(); } },
                { "modifiedBy", n => { ModifiedBy = n.GetStringValue(); } },
                { "orderGroupName", n => { OrderGroupName = n.GetStringValue(); } },
                { "originalTemplateOrderId", n => { OriginalTemplateOrderId = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "templateOrderIds", n => { TemplateOrderIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "templateOrderMaps", n => { TemplateOrderMaps = n.GetObjectValue<global::RIoT.Sdk.Generated.Order.Models.OrderGroupObject_templateOrderMaps>(global::RIoT.Sdk.Generated.Order.Models.OrderGroupObject_templateOrderMaps.CreateFromDiscriminatorValue); } },
                { "userId", n => { UserId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("appointExecuteTime", AppointExecuteTime);
            writer.WriteIntValue("appointVehicleGroupId", AppointVehicleGroupId);
            writer.WriteStringValue("appointVehicleKey", AppointVehicleKey);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteDateTimeOffsetValue("gmtCreate", GmtCreate);
            writer.WriteDateTimeOffsetValue("gmtModified", GmtModified);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("isAppointEnable", IsAppointEnable);
            writer.WriteIntValue("isDeleted", IsDeleted);
            writer.WriteStringValue("modifiedBy", ModifiedBy);
            writer.WriteStringValue("orderGroupName", OrderGroupName);
            writer.WriteStringValue("originalTemplateOrderId", OriginalTemplateOrderId);
            writer.WriteIntValue("priority", Priority);
            writer.WriteCollectionOfPrimitiveValues<int?>("templateOrderIds", TemplateOrderIds);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.Order.Models.OrderGroupObject_templateOrderMaps>("templateOrderMaps", TemplateOrderMaps);
            writer.WriteIntValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
