// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Order.Models
{
    /// <summary>
    /// 订单任务表
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrderMissionObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>动作类型id</summary>
        public int? ActionId { get; set; }
        /// <summary>动作名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionName { get; set; }
#nullable restore
#else
        public string ActionName { get; set; }
#endif
        /// <summary>动作参数1</summary>
        public int? ActionParam1 { get; set; }
        /// <summary>动作参数2</summary>
        public int? ActionParam2 { get; set; }
        /// <summary>动作参数字符串</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionParamStr { get; set; }
#nullable restore
#else
        public string ActionParamStr { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>创建时间</summary>
        public DateTimeOffset? CreateTime { get; set; }
        /// <summary>子任务创建方式:0(外部创建),1(系统自动创建)</summary>
        public int? CreateType { get; set; }
        /// <summary>目的地</summary>
        public int? Destination { get; set; }
        /// <summary>目的地</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationName { get; set; }
#nullable restore
#else
        public string DestinationName { get; set; }
#endif
        /// <summary>子任务执行时间</summary>
        public DateTimeOffset? ExecuteTime { get; set; }
        /// <summary>当前任务系列号</summary>
        public int? ExecutingIndex { get; set; }
        /// <summary>拓展参数</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.Order.Models.OrderMissionObject_extendParams? ExtendParams { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.Order.Models.OrderMissionObject_extendParams ExtendParams { get; set; }
#endif
        /// <summary>子任务执行失败的策略</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailStrategy { get; set; }
#nullable restore
#else
        public string FailStrategy { get; set; }
#endif
        /// <summary>失败策略对应的参数</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailValue { get; set; }
#nullable restore
#else
        public string FailValue { get; set; }
#endif
        /// <summary>子任务完成时间</summary>
        public DateTimeOffset? FinishTime { get; set; }
        /// <summary>关联物模型定义的动作服务key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FunctionKey { get; set; }
#nullable restore
#else
        public string FunctionKey { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>操作子任务的索引</summary>
        public int? Index { get; set; }
        /// <summary>是否删除</summary>
        public int? IsDeleted { get; set; }
        /// <summary>当前任务车长mm</summary>
        public int? Length { get; set; }
        /// <summary>地图id</summary>
        public int? MapId { get; set; }
        /// <summary>地图名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MapName { get; set; }
#nullable restore
#else
        public string MapName { get; set; }
#endif
        /// <summary>0:na，1:执行中，2:完成，3:失败，4:取消</summary>
        public int? MissionState { get; set; }
        /// <summary>订单id</summary>
        public int? OrderId { get; set; }
        /// <summary>上层系统给每一个子任务定义的唯一id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderUuid { get; set; }
#nullable restore
#else
        public string OrderUuid { get; set; }
#endif
        /// <summary>子任务执行结果状态</summary>
        public int? ResultCode { get; set; }
        /// <summary>子任务执行结果</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultStr { get; set; }
#nullable restore
#else
        public string ResultStr { get; set; }
#endif
        /// <summary>当前任务指定速度m/s</summary>
        public float? Speed { get; set; }
        /// <summary>子任务执行成功的策略</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SuccessStrategy { get; set; }
#nullable restore
#else
        public string SuccessStrategy { get; set; }
#endif
        /// <summary>任务类型</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>最后更新时间</summary>
        public DateTimeOffset? UpdateTime { get; set; }
        /// <summary>当前任务车宽mm</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Models.OrderMissionObject"/> and sets the default values.
        /// </summary>
        public OrderMissionObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Models.OrderMissionObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Order.Models.OrderMissionObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Order.Models.OrderMissionObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actionId", n => { ActionId = n.GetIntValue(); } },
                { "actionName", n => { ActionName = n.GetStringValue(); } },
                { "actionParam1", n => { ActionParam1 = n.GetIntValue(); } },
                { "actionParam2", n => { ActionParam2 = n.GetIntValue(); } },
                { "actionParamStr", n => { ActionParamStr = n.GetStringValue(); } },
                { "createTime", n => { CreateTime = n.GetDateTimeOffsetValue(); } },
                { "createType", n => { CreateType = n.GetIntValue(); } },
                { "destination", n => { Destination = n.GetIntValue(); } },
                { "destinationName", n => { DestinationName = n.GetStringValue(); } },
                { "executeTime", n => { ExecuteTime = n.GetDateTimeOffsetValue(); } },
                { "executingIndex", n => { ExecutingIndex = n.GetIntValue(); } },
                { "extendParams", n => { ExtendParams = n.GetObjectValue<global::RIoT.Sdk.Generated.Order.Models.OrderMissionObject_extendParams>(global::RIoT.Sdk.Generated.Order.Models.OrderMissionObject_extendParams.CreateFromDiscriminatorValue); } },
                { "failStrategy", n => { FailStrategy = n.GetStringValue(); } },
                { "failValue", n => { FailValue = n.GetStringValue(); } },
                { "finishTime", n => { FinishTime = n.GetDateTimeOffsetValue(); } },
                { "functionKey", n => { FunctionKey = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "isDeleted", n => { IsDeleted = n.GetIntValue(); } },
                { "length", n => { Length = n.GetIntValue(); } },
                { "mapId", n => { MapId = n.GetIntValue(); } },
                { "mapName", n => { MapName = n.GetStringValue(); } },
                { "missionState", n => { MissionState = n.GetIntValue(); } },
                { "orderId", n => { OrderId = n.GetIntValue(); } },
                { "orderUuid", n => { OrderUuid = n.GetStringValue(); } },
                { "resultCode", n => { ResultCode = n.GetIntValue(); } },
                { "resultStr", n => { ResultStr = n.GetStringValue(); } },
                { "speed", n => { Speed = n.GetFloatValue(); } },
                { "successStrategy", n => { SuccessStrategy = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "updateTime", n => { UpdateTime = n.GetDateTimeOffsetValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("actionId", ActionId);
            writer.WriteStringValue("actionName", ActionName);
            writer.WriteIntValue("actionParam1", ActionParam1);
            writer.WriteIntValue("actionParam2", ActionParam2);
            writer.WriteStringValue("actionParamStr", ActionParamStr);
            writer.WriteDateTimeOffsetValue("createTime", CreateTime);
            writer.WriteIntValue("createType", CreateType);
            writer.WriteIntValue("destination", Destination);
            writer.WriteStringValue("destinationName", DestinationName);
            writer.WriteDateTimeOffsetValue("executeTime", ExecuteTime);
            writer.WriteIntValue("executingIndex", ExecutingIndex);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.Order.Models.OrderMissionObject_extendParams>("extendParams", ExtendParams);
            writer.WriteStringValue("failStrategy", FailStrategy);
            writer.WriteStringValue("failValue", FailValue);
            writer.WriteDateTimeOffsetValue("finishTime", FinishTime);
            writer.WriteStringValue("functionKey", FunctionKey);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("index", Index);
            writer.WriteIntValue("isDeleted", IsDeleted);
            writer.WriteIntValue("length", Length);
            writer.WriteIntValue("mapId", MapId);
            writer.WriteStringValue("mapName", MapName);
            writer.WriteIntValue("missionState", MissionState);
            writer.WriteIntValue("orderId", OrderId);
            writer.WriteStringValue("orderUuid", OrderUuid);
            writer.WriteIntValue("resultCode", ResultCode);
            writer.WriteStringValue("resultStr", ResultStr);
            writer.WriteFloatValue("speed", Speed);
            writer.WriteStringValue("successStrategy", SuccessStrategy);
            writer.WriteStringValue("type", Type);
            writer.WriteDateTimeOffsetValue("updateTime", UpdateTime);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
