// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Order.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TagPageVo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>模板标签id</summary>
        public int? Id { get; set; }
        /// <summary>标签名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TagName { get; set; }
#nullable restore
#else
        public string TagName { get; set; }
#endif
        /// <summary>模板个数</summary>
        public int? TagNum { get; set; }
        /// <summary>模板订单</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.Order.Models.TemplateOrderObject>? TemplateOrders { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.Order.Models.TemplateOrderObject> TemplateOrders { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Models.TagPageVo"/> and sets the default values.
        /// </summary>
        public TagPageVo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Models.TagPageVo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Order.Models.TagPageVo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Order.Models.TagPageVo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetIntValue(); } },
                { "tagName", n => { TagName = n.GetStringValue(); } },
                { "tagNum", n => { TagNum = n.GetIntValue(); } },
                { "templateOrders", n => { TemplateOrders = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.Order.Models.TemplateOrderObject>(global::RIoT.Sdk.Generated.Order.Models.TemplateOrderObject.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("tagName", TagName);
            writer.WriteIntValue("tagNum", TagNum);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.Order.Models.TemplateOrderObject>("templateOrders", TemplateOrders);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
