// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Order.Models
{
    /// <summary>
    /// 分页查询模板标签返回给前端的实体类
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TemplateOrderTagPageVOObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current property</summary>
        public long? Current { get; set; }
        /// <summary>The pages property</summary>
        public long? Pages { get; set; }
        /// <summary>The records property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.Order.Models.TagPageVo>? Records { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.Order.Models.TagPageVo> Records { get; set; }
#endif
        /// <summary>The size property</summary>
        public long? Size { get; set; }
        /// <summary>The total property</summary>
        public long? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Models.TemplateOrderTagPageVOObject"/> and sets the default values.
        /// </summary>
        public TemplateOrderTagPageVOObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Models.TemplateOrderTagPageVOObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Order.Models.TemplateOrderTagPageVOObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Order.Models.TemplateOrderTagPageVOObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current", n => { Current = n.GetLongValue(); } },
                { "pages", n => { Pages = n.GetLongValue(); } },
                { "records", n => { Records = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.Order.Models.TagPageVo>(global::RIoT.Sdk.Generated.Order.Models.TagPageVo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "total", n => { Total = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("current", Current);
            writer.WriteLongValue("pages", Pages);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.Order.Models.TagPageVo>("records", Records);
            writer.WriteLongValue("size", Size);
            writer.WriteLongValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
