// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Order.Models
{
    /// <summary>
    /// UpdateOrderRecord对象
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateOrderRecordObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>车辆key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceKey { get; set; }
#nullable restore
#else
        public string DeviceKey { get; set; }
#endif
        /// <summary>默认mission</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.Order.Models.UpdateMission>? Missions { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.Order.Models.UpdateMission> Missions { get; set; }
#endif
        /// <summary>订单的key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderKey { get; set; }
#nullable restore
#else
        public string OrderKey { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Models.UpdateOrderRecordObject"/> and sets the default values.
        /// </summary>
        public UpdateOrderRecordObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Models.UpdateOrderRecordObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Order.Models.UpdateOrderRecordObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Order.Models.UpdateOrderRecordObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "deviceKey", n => { DeviceKey = n.GetStringValue(); } },
                { "missions", n => { Missions = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.Order.Models.UpdateMission>(global::RIoT.Sdk.Generated.Order.Models.UpdateMission.CreateFromDiscriminatorValue)?.AsList(); } },
                { "orderKey", n => { OrderKey = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("deviceKey", DeviceKey);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.Order.Models.UpdateMission>("missions", Missions);
            writer.WriteStringValue("orderKey", OrderKey);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
