// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Device.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups
{
    /// <summary>
    /// Builds and executes requests for operations under \api\device\v1\group\queryDevicesGroups
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QueryDevicesGroupsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups.QueryDevicesGroupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueryDevicesGroupsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device/v1/group/queryDevicesGroups{?groupName*,order*,orderBy*,pageNum*,pageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups.QueryDevicesGroupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueryDevicesGroupsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device/v1/group/queryDevicesGroups{?groupName*,order*,orderBy*,pageNum*,pageSize*}", rawUrl)
        {
        }
        /// <summary>
        /// queryDevicesGroups
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Models.ResponseMsg_Of_Page_Of_DeviceGroupDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RIoT.Sdk.Generated.Device.Models.ResponseMsg_Of_Page_Of_DeviceGroupDto?> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups.QueryDevicesGroupsRequestBuilder.QueryDevicesGroupsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RIoT.Sdk.Generated.Device.Models.ResponseMsg_Of_Page_Of_DeviceGroupDto> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups.QueryDevicesGroupsRequestBuilder.QueryDevicesGroupsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::RIoT.Sdk.Generated.Device.Models.ResponseMsg_Of_Page_Of_DeviceGroupDto>(requestInfo, global::RIoT.Sdk.Generated.Device.Models.ResponseMsg_Of_Page_Of_DeviceGroupDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// queryDevicesGroups
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups.QueryDevicesGroupsRequestBuilder.QueryDevicesGroupsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups.QueryDevicesGroupsRequestBuilder.QueryDevicesGroupsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups.QueryDevicesGroupsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups.QueryDevicesGroupsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups.QueryDevicesGroupsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// queryDevicesGroups
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QueryDevicesGroupsRequestBuilderGetQueryParameters 
        {
            /// <summary>机器人组名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("groupName")]
            public string? GroupName { get; set; }
#nullable restore
#else
            [QueryParameter("groupName")]
            public string GroupName { get; set; }
#endif
            /// <summary>正序倒序（DESC为降序，ASC为正序）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>排序的列名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderBy")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("orderBy")]
            public string OrderBy { get; set; }
#endif
            /// <summary>页码</summary>
            [QueryParameter("pageNum")]
            public int? PageNum { get; set; }
            /// <summary>页尺寸</summary>
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QueryDevicesGroupsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::RIoT.Sdk.Generated.Device.Api.Device.V1.Group.QueryDevicesGroups.QueryDevicesGroupsRequestBuilder.QueryDevicesGroupsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
