// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearAllVehicle;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearOrderSequence;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearVehicle;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearVehicleAndCancelOrderTask;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.GetVehicleInfo;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.TestPlay;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\v1\task
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaskRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The clearAllVehicle property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearAllVehicle.ClearAllVehicleRequestBuilder ClearAllVehicle
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearAllVehicle.ClearAllVehicleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The clearOrderSequence property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearOrderSequence.ClearOrderSequenceRequestBuilder ClearOrderSequence
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearOrderSequence.ClearOrderSequenceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The clearVehicle property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearVehicle.ClearVehicleRequestBuilder ClearVehicle
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearVehicle.ClearVehicleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The clearVehicleAndCancelOrderTask property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearVehicleAndCancelOrderTask.ClearVehicleAndCancelOrderTaskRequestBuilder ClearVehicleAndCancelOrderTask
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ClearVehicleAndCancelOrderTask.ClearVehicleAndCancelOrderTaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The execActionCommand property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.ExecActionCommandRequestBuilder ExecActionCommand
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.ExecActionCommandRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getVehicleInfo property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.GetVehicleInfo.GetVehicleInfoRequestBuilder GetVehicleInfo
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.GetVehicleInfo.GetVehicleInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The testPlay property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.TestPlay.TestPlayRequestBuilder TestPlay
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.TestPlay.TestPlayRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.TaskRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaskRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/task", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.TaskRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaskRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/task", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
