// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Imap.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord
{
    /// <summary>
    /// Builds and executes requests for operations under \api\imap\v1\mapSyncRecord\
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmptyPathSegmentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.EmptyPathSegmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmptyPathSegmentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imap/v1/mapSyncRecord/{?keyword*,mapSyncSource*,mapSyncType*,order*,orderBy*,pageNum*,pageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.EmptyPathSegmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmptyPathSegmentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imap/v1/mapSyncRecord/{?keyword*,mapSyncSource*,mapSyncType*,order*,orderBy*,pageNum*,pageSize*}", rawUrl)
        {
        }
        /// <summary>
        /// 查询地图同步信息
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Page_Of_MapSyncRecordObject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Page_Of_MapSyncRecordObject?> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Page_Of_MapSyncRecordObject> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Page_Of_MapSyncRecordObject>(requestInfo, global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Page_Of_MapSyncRecordObject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 查询地图同步信息
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.EmptyPathSegmentRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.EmptyPathSegmentRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.EmptyPathSegmentRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 查询地图同步信息
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EmptyPathSegmentRequestBuilderGetQueryParameters 
        {
            /// <summary>搜索关键词</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("keyword")]
            public string? Keyword { get; set; }
#nullable restore
#else
            [QueryParameter("keyword")]
            public string Keyword { get; set; }
#endif
            /// <summary>同步来源</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("mapSyncSource")]
            public string? MapSyncSource { get; set; }
#nullable restore
#else
            [QueryParameter("mapSyncSource")]
            public string MapSyncSource { get; set; }
#endif
            /// <summary>同步类型</summary>
            [Obsolete("This property is deprecated, use MapSyncTypeAsGetMapSyncTypeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("mapSyncType")]
            public string? MapSyncType { get; set; }
#nullable restore
#else
            [QueryParameter("mapSyncType")]
            public string MapSyncType { get; set; }
#endif
            /// <summary>同步类型</summary>
            [QueryParameter("mapSyncType")]
            public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.GetMapSyncTypeQueryParameterType? MapSyncTypeAsGetMapSyncTypeQueryParameterType { get; set; }
            /// <summary>正序倒序（DESC为降序，ASC为正序）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>排序的列名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderBy")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("orderBy")]
            public string OrderBy { get; set; }
#endif
            /// <summary>页码</summary>
            [QueryParameter("pageNum")]
            public int? PageNum { get; set; }
            /// <summary>页尺寸</summary>
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EmptyPathSegmentRequestBuilderGetRequestConfiguration : RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapSyncRecord.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
