// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Device.Models
{
    /// <summary>
    /// 设备组信息
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceGroupObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>创建人</summary>
        public long? CreateBy { get; set; }
        /// <summary>是否删除</summary>
        public bool? Deleted { get; set; }
        /// <summary>车辆组名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceGroupName { get; set; }
#nullable restore
#else
        public string DeviceGroupName { get; set; }
#endif
        /// <summary>自增id</summary>
        public long? Id { get; set; }
        /// <summary>长</summary>
        public int? Length { get; set; }
        /// <summary>载货时长</summary>
        public int? LengthLoaded { get; set; }
        /// <summary>描述</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remark { get; set; }
#nullable restore
#else
        public string Remark { get; set; }
#endif
        /// <summary>类型</summary>
        public int? Type { get; set; }
        /// <summary>更新人</summary>
        public long? UpdateBy { get; set; }
        /// <summary>宽</summary>
        public int? Width { get; set; }
        /// <summary>载货时宽</summary>
        public int? WidthLoaded { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Models.DeviceGroupObject"/> and sets the default values.
        /// </summary>
        public DeviceGroupObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Models.DeviceGroupObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Device.Models.DeviceGroupObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Device.Models.DeviceGroupObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createBy", n => { CreateBy = n.GetLongValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "deviceGroupName", n => { DeviceGroupName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "length", n => { Length = n.GetIntValue(); } },
                { "lengthLoaded", n => { LengthLoaded = n.GetIntValue(); } },
                { "remark", n => { Remark = n.GetStringValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
                { "updateBy", n => { UpdateBy = n.GetLongValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
                { "widthLoaded", n => { WidthLoaded = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("createBy", CreateBy);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteStringValue("deviceGroupName", DeviceGroupName);
            writer.WriteLongValue("id", Id);
            writer.WriteIntValue("length", Length);
            writer.WriteIntValue("lengthLoaded", LengthLoaded);
            writer.WriteStringValue("remark", Remark);
            writer.WriteIntValue("type", Type);
            writer.WriteLongValue("updateBy", UpdateBy);
            writer.WriteIntValue("width", Width);
            writer.WriteIntValue("widthLoaded", WidthLoaded);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
