// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Device.Models
{
    /// <summary>
    /// 设备信息
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>创建人</summary>
        public long? CreateBy { get; set; }
        /// <summary>是否删除</summary>
        public bool? Deleted { get; set; }
        /// <summary>设备Key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceKey { get; set; }
#nullable restore
#else
        public string DeviceKey { get; set; }
#endif
        /// <summary>[require] 备注名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceName { get; set; }
#nullable restore
#else
        public string DeviceName { get; set; }
#endif
        /// <summary>设备密钥</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceSecret { get; set; }
#nullable restore
#else
        public string DeviceSecret { get; set; }
#endif
        /// <summary>设备序列号</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceSerialNo { get; set; }
#nullable restore
#else
        public string DeviceSerialNo { get; set; }
#endif
        /// <summary>设备类型;1:AGV 2:生产设备 3:非生产设备</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceType { get; set; }
#nullable restore
#else
        public string DeviceType { get; set; }
#endif
        /// <summary>是否禁用</summary>
        public bool? Enable { get; set; }
        /// <summary>启用、禁用修改时间</summary>
        public DateTimeOffset? EnableUpdateTime { get; set; }
        /// <summary>记录生成时间</summary>
        public DateTimeOffset? GmtCreate { get; set; }
        /// <summary>更新时间</summary>
        public DateTimeOffset? GmtModified { get; set; }
        /// <summary>设备作为server端时需要指定，ip:port</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HostPort { get; set; }
#nullable restore
#else
        public string HostPort { get; set; }
#endif
        /// <summary>自增id</summary>
        public long? Id { get; set; }
        /// <summary>设备状态上报时间</summary>
        public DateTimeOffset? LastStatusReportTime { get; set; }
        /// <summary>产品型号</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>物模型版本号</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModelVersion { get; set; }
#nullable restore
#else
        public string ModelVersion { get; set; }
#endif
        /// <summary>节点类型</summary>
        public int? NodeType { get; set; }
        /// <summary>父产品名称（网关）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentDeviceKey { get; set; }
#nullable restore
#else
        public string ParentDeviceKey { get; set; }
#endif
        /// <summary>设备作为client端时需要指定，设备物理id,如mac地址、ip</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhysicsId { get; set; }
#nullable restore
#else
        public string PhysicsId { get; set; }
#endif
        /// <summary>[require] 关联产品Key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductKey { get; set; }
#nullable restore
#else
        public string ProductKey { get; set; }
#endif
        /// <summary>设备说明</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemarkName { get; set; }
#nullable restore
#else
        public string RemarkName { get; set; }
#endif
        /// <summary>产品系列</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Series { get; set; }
#nullable restore
#else
        public string Series { get; set; }
#endif
        /// <summary>设备上下线状态</summary>
        public int? Status { get; set; }
        /// <summary>更新人</summary>
        public long? UpdateBy { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Models.DeviceObject"/> and sets the default values.
        /// </summary>
        public DeviceObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Models.DeviceObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Device.Models.DeviceObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Device.Models.DeviceObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createBy", n => { CreateBy = n.GetLongValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "deviceKey", n => { DeviceKey = n.GetStringValue(); } },
                { "deviceName", n => { DeviceName = n.GetStringValue(); } },
                { "deviceSecret", n => { DeviceSecret = n.GetStringValue(); } },
                { "deviceSerialNo", n => { DeviceSerialNo = n.GetStringValue(); } },
                { "deviceType", n => { DeviceType = n.GetStringValue(); } },
                { "enable", n => { Enable = n.GetBoolValue(); } },
                { "enableUpdateTime", n => { EnableUpdateTime = n.GetDateTimeOffsetValue(); } },
                { "gmtCreate", n => { GmtCreate = n.GetDateTimeOffsetValue(); } },
                { "gmtModified", n => { GmtModified = n.GetDateTimeOffsetValue(); } },
                { "hostPort", n => { HostPort = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "lastStatusReportTime", n => { LastStatusReportTime = n.GetDateTimeOffsetValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "modelVersion", n => { ModelVersion = n.GetStringValue(); } },
                { "nodeType", n => { NodeType = n.GetIntValue(); } },
                { "parentDeviceKey", n => { ParentDeviceKey = n.GetStringValue(); } },
                { "physicsId", n => { PhysicsId = n.GetStringValue(); } },
                { "productKey", n => { ProductKey = n.GetStringValue(); } },
                { "remarkName", n => { RemarkName = n.GetStringValue(); } },
                { "series", n => { Series = n.GetStringValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "updateBy", n => { UpdateBy = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("createBy", CreateBy);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteStringValue("deviceKey", DeviceKey);
            writer.WriteStringValue("deviceName", DeviceName);
            writer.WriteStringValue("deviceSecret", DeviceSecret);
            writer.WriteStringValue("deviceSerialNo", DeviceSerialNo);
            writer.WriteStringValue("deviceType", DeviceType);
            writer.WriteBoolValue("enable", Enable);
            writer.WriteDateTimeOffsetValue("enableUpdateTime", EnableUpdateTime);
            writer.WriteDateTimeOffsetValue("gmtCreate", GmtCreate);
            writer.WriteDateTimeOffsetValue("gmtModified", GmtModified);
            writer.WriteStringValue("hostPort", HostPort);
            writer.WriteLongValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastStatusReportTime", LastStatusReportTime);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("modelVersion", ModelVersion);
            writer.WriteIntValue("nodeType", NodeType);
            writer.WriteStringValue("parentDeviceKey", ParentDeviceKey);
            writer.WriteStringValue("physicsId", PhysicsId);
            writer.WriteStringValue("productKey", ProductKey);
            writer.WriteStringValue("remarkName", RemarkName);
            writer.WriteStringValue("series", Series);
            writer.WriteIntValue("status", Status);
            writer.WriteLongValue("updateBy", UpdateBy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
