// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.Device.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum HttpCallback_requestMethod
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CONNECT")]
        #pragma warning disable CS1591
        CONNECT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETE")]
        #pragma warning disable CS1591
        DELETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "GET")]
        #pragma warning disable CS1591
        GET,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEAD")]
        #pragma warning disable CS1591
        HEAD,
        #pragma warning restore CS1591
        [EnumMember(Value = "OPTIONS")]
        #pragma warning disable CS1591
        OPTIONS,
        #pragma warning restore CS1591
        [EnumMember(Value = "PATCH")]
        #pragma warning disable CS1591
        PATCH,
        #pragma warning restore CS1591
        [EnumMember(Value = "POST")]
        #pragma warning disable CS1591
        POST,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUT")]
        #pragma warning disable CS1591
        PUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRACE")]
        #pragma warning disable CS1591
        TRACE,
        #pragma warning restore CS1591
    }
}
