// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.Device.Models
{
    /// <summary>连网方式 可选值: 2:Wi-Fi 6:CELLULAR 蜂窝网 7:ETHERNET 以太网 8:LORA(LoRaWAN)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProductObject_netType
    {
        [EnumMember(Value = "CELLULAR")]
        #pragma warning disable CS1591
        CELLULAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "ETHERNET")]
        #pragma warning disable CS1591
        ETHERNET,
        #pragma warning restore CS1591
        [EnumMember(Value = "LORA")]
        #pragma warning disable CS1591
        LORA,
        #pragma warning restore CS1591
        [EnumMember(Value = "WIFI")]
        #pragma warning disable CS1591
        WIFI,
        #pragma warning restore CS1591
    }
}
