// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.Device.Models
{
    /// <summary>数据格式 0:custom_format; 1:srlink_format</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProductObject_dataFormat
    {
        [EnumMember(Value = "CUSTOM_FORMAT")]
        #pragma warning disable CS1591
        CUSTOM_FORMAT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SRLINK_FORMAT")]
        #pragma warning disable CS1591
        SRLINK_FORMAT,
        #pragma warning restore CS1591
    }
}
