// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Device.Models
{
    /// <summary>
    /// 产品表
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>产品下的设备接入物联网平台的认证方式: DeviceSecret</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthType { get; set; }
#nullable restore
#else
        public string AuthType { get; set; }
#endif
        /// <summary>产品品类的标识符。如果传入此参数，创建的产品将使用指定品类的物模型；不传入，则不使用任何品类的标准物模型</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CategoryKey { get; set; }
#nullable restore
#else
        public string CategoryKey { get; set; }
#endif
        /// <summary>创建用户</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>数据格式 0:custom_format; 1:srlink_format</summary>
        public global::RIoT.Sdk.Generated.Device.Models.ProductObject_dataFormat? DataFormat { get; set; }
        /// <summary>The deleted property</summary>
        public bool? Deleted { get; set; }
        /// <summary>产品描述</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>创建时间</summary>
        public DateTimeOffset? GmtCreate { get; set; }
        /// <summary>更新时间</summary>
        public DateTimeOffset? GmtModified { get; set; }
        /// <summary>该版产品发布的时间</summary>
        public DateTimeOffset? GmtRelease { get; set; }
        /// <summary>主键ID</summary>
        public int? Id { get; set; }
        /// <summary>产品图片</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageUrl { get; set; }
#nullable restore
#else
        public string ImageUrl { get; set; }
#endif
        /// <summary>入网凭证ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JoinPermissionId { get; set; }
#nullable restore
#else
        public string JoinPermissionId { get; set; }
#endif
        /// <summary>更新用户</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModifiedBy { get; set; }
#nullable restore
#else
        public string ModifiedBy { get; set; }
#endif
        /// <summary>连网方式 可选值: 2:Wi-Fi 6:CELLULAR 蜂窝网 7:ETHERNET 以太网 8:LORA(LoRaWAN)</summary>
        public global::RIoT.Sdk.Generated.Device.Models.ProductObject_netType? NetType { get; set; }
        /// <summary>节点类型: 1-直连设备 2-网关设备 3-网关子设备</summary>
        public global::RIoT.Sdk.Generated.Device.Models.ProductObject_nodeType? NodeType { get; set; }
        /// <summary>物联网平台为新建产品颁发的产品Key，作为该产品的全局唯一标识</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductKey { get; set; }
#nullable restore
#else
        public string ProductKey { get; set; }
#endif
        /// <summary>产品名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductName { get; set; }
#nullable restore
#else
        public string ProductName { get; set; }
#endif
        /// <summary>产品密钥</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductSecret { get; set; }
#nullable restore
#else
        public string ProductSecret { get; set; }
#endif
        /// <summary>设备接入网关的协议类型 modbus opc-ua customize(自定义协议) ble(BLE协议) zigbee</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProtocolType { get; set; }
#nullable restore
#else
        public string ProtocolType { get; set; }
#endif
        /// <summary>注册状态 未上线(1)/已上线(2)/撤销(3)</summary>
        public global::RIoT.Sdk.Generated.Device.Models.ProductObject_status? Status { get; set; }
        /// <summary>是否标准品类</summary>
        public bool? Templates { get; set; }
        /// <summary>租户ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantId { get; set; }
#nullable restore
#else
        public string TenantId { get; set; }
#endif
        /// <summary>产品类型</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.Device.Models.ProductTypesObject>? TypesList { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.Device.Models.ProductTypesObject> TypesList { get; set; }
#endif
        /// <summary>数据校验级别: 1,强校验；2,弱校验；3,免校验</summary>
        public global::RIoT.Sdk.Generated.Device.Models.ProductObject_validateType? ValidateType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Models.ProductObject"/> and sets the default values.
        /// </summary>
        public ProductObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Models.ProductObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Device.Models.ProductObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Device.Models.ProductObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authType", n => { AuthType = n.GetStringValue(); } },
                { "categoryKey", n => { CategoryKey = n.GetStringValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "dataFormat", n => { DataFormat = n.GetEnumValue<global::RIoT.Sdk.Generated.Device.Models.ProductObject_dataFormat>(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "gmtCreate", n => { GmtCreate = n.GetDateTimeOffsetValue(); } },
                { "gmtModified", n => { GmtModified = n.GetDateTimeOffsetValue(); } },
                { "gmtRelease", n => { GmtRelease = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "imageUrl", n => { ImageUrl = n.GetStringValue(); } },
                { "joinPermissionId", n => { JoinPermissionId = n.GetStringValue(); } },
                { "modifiedBy", n => { ModifiedBy = n.GetStringValue(); } },
                { "netType", n => { NetType = n.GetEnumValue<global::RIoT.Sdk.Generated.Device.Models.ProductObject_netType>(); } },
                { "nodeType", n => { NodeType = n.GetEnumValue<global::RIoT.Sdk.Generated.Device.Models.ProductObject_nodeType>(); } },
                { "productKey", n => { ProductKey = n.GetStringValue(); } },
                { "productName", n => { ProductName = n.GetStringValue(); } },
                { "productSecret", n => { ProductSecret = n.GetStringValue(); } },
                { "protocolType", n => { ProtocolType = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::RIoT.Sdk.Generated.Device.Models.ProductObject_status>(); } },
                { "templates", n => { Templates = n.GetBoolValue(); } },
                { "tenantId", n => { TenantId = n.GetStringValue(); } },
                { "typesList", n => { TypesList = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.Device.Models.ProductTypesObject>(global::RIoT.Sdk.Generated.Device.Models.ProductTypesObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "validateType", n => { ValidateType = n.GetEnumValue<global::RIoT.Sdk.Generated.Device.Models.ProductObject_validateType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("authType", AuthType);
            writer.WriteStringValue("categoryKey", CategoryKey);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteEnumValue<global::RIoT.Sdk.Generated.Device.Models.ProductObject_dataFormat>("dataFormat", DataFormat);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("gmtCreate", GmtCreate);
            writer.WriteDateTimeOffsetValue("gmtModified", GmtModified);
            writer.WriteDateTimeOffsetValue("gmtRelease", GmtRelease);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("imageUrl", ImageUrl);
            writer.WriteStringValue("joinPermissionId", JoinPermissionId);
            writer.WriteStringValue("modifiedBy", ModifiedBy);
            writer.WriteEnumValue<global::RIoT.Sdk.Generated.Device.Models.ProductObject_netType>("netType", NetType);
            writer.WriteEnumValue<global::RIoT.Sdk.Generated.Device.Models.ProductObject_nodeType>("nodeType", NodeType);
            writer.WriteStringValue("productKey", ProductKey);
            writer.WriteStringValue("productName", ProductName);
            writer.WriteStringValue("productSecret", ProductSecret);
            writer.WriteStringValue("protocolType", ProtocolType);
            writer.WriteEnumValue<global::RIoT.Sdk.Generated.Device.Models.ProductObject_status>("status", Status);
            writer.WriteBoolValue("templates", Templates);
            writer.WriteStringValue("tenantId", TenantId);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.Device.Models.ProductTypesObject>("typesList", TypesList);
            writer.WriteEnumValue<global::RIoT.Sdk.Generated.Device.Models.ProductObject_validateType>("validateType", ValidateType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
