// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RIoT.Sdk.Generated.Device.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ThingModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The events property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.Device.Models.Event>? Events { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.Device.Models.Event> Events { get; set; }
#endif
        /// <summary>The extendConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.Device.Models.ExtendConfig? ExtendConfig { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.Device.Models.ExtendConfig ExtendConfig { get; set; }
#endif
        /// <summary>The functionBlockId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FunctionBlockId { get; set; }
#nullable restore
#else
        public string FunctionBlockId { get; set; }
#endif
        /// <summary>The functionBlockName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FunctionBlockName { get; set; }
#nullable restore
#else
        public string FunctionBlockName { get; set; }
#endif
        /// <summary>The functionBlocks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.Device.Models.FunctionBlock>? FunctionBlocks { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.Device.Models.FunctionBlock> FunctionBlocks { get; set; }
#endif
        /// <summary>The profile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RIoT.Sdk.Generated.Device.Models.Profile? Profile { get; set; }
#nullable restore
#else
        public global::RIoT.Sdk.Generated.Device.Models.Profile Profile { get; set; }
#endif
        /// <summary>The properties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.Device.Models.Property>? Properties { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.Device.Models.Property> Properties { get; set; }
#endif
        /// <summary>The services property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RIoT.Sdk.Generated.Device.Models.Service>? Services { get; set; }
#nullable restore
#else
        public List<global::RIoT.Sdk.Generated.Device.Models.Service> Services { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Device.Models.ThingModel"/> and sets the default values.
        /// </summary>
        public ThingModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Device.Models.ThingModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RIoT.Sdk.Generated.Device.Models.ThingModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RIoT.Sdk.Generated.Device.Models.ThingModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "events", n => { Events = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.Device.Models.Event>(global::RIoT.Sdk.Generated.Device.Models.Event.CreateFromDiscriminatorValue)?.AsList(); } },
                { "extendConfig", n => { ExtendConfig = n.GetObjectValue<global::RIoT.Sdk.Generated.Device.Models.ExtendConfig>(global::RIoT.Sdk.Generated.Device.Models.ExtendConfig.CreateFromDiscriminatorValue); } },
                { "functionBlockId", n => { FunctionBlockId = n.GetStringValue(); } },
                { "functionBlockName", n => { FunctionBlockName = n.GetStringValue(); } },
                { "functionBlocks", n => { FunctionBlocks = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.Device.Models.FunctionBlock>(global::RIoT.Sdk.Generated.Device.Models.FunctionBlock.CreateFromDiscriminatorValue)?.AsList(); } },
                { "profile", n => { Profile = n.GetObjectValue<global::RIoT.Sdk.Generated.Device.Models.Profile>(global::RIoT.Sdk.Generated.Device.Models.Profile.CreateFromDiscriminatorValue); } },
                { "properties", n => { Properties = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.Device.Models.Property>(global::RIoT.Sdk.Generated.Device.Models.Property.CreateFromDiscriminatorValue)?.AsList(); } },
                { "services", n => { Services = n.GetCollectionOfObjectValues<global::RIoT.Sdk.Generated.Device.Models.Service>(global::RIoT.Sdk.Generated.Device.Models.Service.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.Device.Models.Event>("events", Events);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.Device.Models.ExtendConfig>("extendConfig", ExtendConfig);
            writer.WriteStringValue("functionBlockId", FunctionBlockId);
            writer.WriteStringValue("functionBlockName", FunctionBlockName);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.Device.Models.FunctionBlock>("functionBlocks", FunctionBlocks);
            writer.WriteObjectValue<global::RIoT.Sdk.Generated.Device.Models.Profile>("profile", Profile);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.Device.Models.Property>("properties", Properties);
            writer.WriteCollectionOfObjectValues<global::RIoT.Sdk.Generated.Device.Models.Service>("services", Services);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
