// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.Item.Item.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.Item.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\v1\task\execActionCommand\{deviceKey}\{actionId}\{param1}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithParam1ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the RIoT.Sdk.Generated.TaskApi.api.task.v1.task.execActionCommand.item.item.item.item collection</summary>
        /// <param name="position">param2</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.Item.Item.Item.Item.WithParam2ItemRequestBuilder"/></returns>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.Item.Item.Item.Item.WithParam2ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("param2", position);
                return new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.Item.Item.Item.Item.WithParam2ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the RIoT.Sdk.Generated.TaskApi.api.task.v1.task.execActionCommand.item.item.item.item collection</summary>
        /// <param name="position">param2</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.Item.Item.Item.Item.WithParam2ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.Item.Item.Item.Item.WithParam2ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("param2", position);
                return new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.Item.Item.Item.Item.WithParam2ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.Item.Item.Item.WithParam1ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithParam1ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/task/execActionCommand/{deviceKey}/{actionId}/{param1}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.TaskNamespace.ExecActionCommand.Item.Item.Item.WithParam1ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithParam1ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/task/execActionCommand/{deviceKey}/{actionId}/{param1}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
