// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Imap.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull
{
    /// <summary>
    /// Builds and executes requests for operations under \api\imap\v1\mapInfo\file\pull
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PullRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PullRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PullRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imap/v1/mapInfo/file/pull?mapName={mapName}&note={note}&state={state}&vehicleIP={vehicleIP}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PullRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PullRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imap/v1/mapInfo/file/pull?mapName={mapName}&note={note}&state={state}&vehicleIP={vehicleIP}", rawUrl)
        {
        }
        /// <summary>
        /// 拉取地图
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Void"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Void?> PostAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PullRequestBuilder.PullRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Void> PostAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PullRequestBuilder.PullRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Void>(requestInfo, global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Void.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 拉取地图
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PullRequestBuilder.PullRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PullRequestBuilder.PullRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PullRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PullRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PullRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 拉取地图
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PullRequestBuilderPostQueryParameters 
        {
            /// <summary>地图名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("mapName")]
            public string? MapName { get; set; }
#nullable restore
#else
            [QueryParameter("mapName")]
            public string MapName { get; set; }
#endif
            /// <summary>备注</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("note")]
            public string? Note { get; set; }
#nullable restore
#else
            [QueryParameter("note")]
            public string Note { get; set; }
#endif
            /// <summary>地图状态</summary>
            [Obsolete("This property is deprecated, use StateAsPostStateQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("state")]
            public string? State { get; set; }
#nullable restore
#else
            [QueryParameter("state")]
            public string State { get; set; }
#endif
            /// <summary>地图状态</summary>
            [QueryParameter("state")]
            public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PostStateQueryParameterType? StateAsPostStateQueryParameterType { get; set; }
            /// <summary>车ip</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("vehicleIP")]
            public string? VehicleIP { get; set; }
#nullable restore
#else
            [QueryParameter("vehicleIP")]
            public string VehicleIP { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PullRequestBuilderPostRequestConfiguration : RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.Pull.PullRequestBuilder.PullRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
