// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStationTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CHARGE_POSITION")]
        #pragma warning disable CS1591
        CHARGE_POSITION,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARK_POSITION")]
        #pragma warning disable CS1591
        PARK_POSITION,
        #pragma warning restore CS1591
    }
}
