// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Imap.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\imap\v1\mapInfo\getStationCustomAttributes\{mapId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithMapItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.WithMapItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMapItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imap/v1/mapInfo/getStationCustomAttributes/{mapId}{?stationType*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.WithMapItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMapItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imap/v1/mapInfo/getStationCustomAttributes/{mapId}{?stationType*}", rawUrl)
        {
        }
        /// <summary>
        /// 获取站点自定义属性
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_List_Of_CustomStation"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_List_Of_CustomStation?> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.WithMapItemRequestBuilder.WithMapItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_List_Of_CustomStation> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.WithMapItemRequestBuilder.WithMapItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_List_Of_CustomStation>(requestInfo, global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_List_Of_CustomStation.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 获取站点自定义属性
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.WithMapItemRequestBuilder.WithMapItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.WithMapItemRequestBuilder.WithMapItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.WithMapItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.WithMapItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.WithMapItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 获取站点自定义属性
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithMapItemRequestBuilderGetQueryParameters 
        {
            /// <summary>stationType</summary>
            [Obsolete("This property is deprecated, use StationTypeAsGetStationTypeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("stationType")]
            public string? StationType { get; set; }
#nullable restore
#else
            [QueryParameter("stationType")]
            public string StationType { get; set; }
#endif
            /// <summary>stationType</summary>
            [QueryParameter("stationType")]
            public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.GetStationTypeQueryParameterType? StationTypeAsGetStationTypeQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithMapItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.GetStationCustomAttributes.Item.WithMapItemRequestBuilder.WithMapItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
