// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord
{
    /// <summary>
    /// Builds and executes requests for operations under \api\order\v1\orderRecord\old\exportOrderRecord
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExportOrderRecordRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord.ExportOrderRecordRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportOrderRecordRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/order/v1/orderRecord/old/exportOrderRecord?pageNum={pageNum}&pageSize={pageSize}{&endStationName*,endStationNo*,endTime*,executeVehicleKey*,executeVehicleName*,filterBySource*,filterByState,order*,orderBy*,orderType,query*,startStationName*,startStationNo*,startTime*,userId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord.ExportOrderRecordRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportOrderRecordRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/order/v1/orderRecord/old/exportOrderRecord?pageNum={pageNum}&pageSize={pageSize}{&endStationName*,endStationNo*,endTime*,executeVehicleKey*,executeVehicleName*,filterBySource*,filterByState,order*,orderBy*,orderType,query*,startStationName*,startStationNo*,startTime*,userId*}", rawUrl)
        {
        }
        /// <summary>
        /// 导出订单记录
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord.ExportOrderRecordRequestBuilder.ExportOrderRecordRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord.ExportOrderRecordRequestBuilder.ExportOrderRecordRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 导出订单记录
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord.ExportOrderRecordRequestBuilder.ExportOrderRecordRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord.ExportOrderRecordRequestBuilder.ExportOrderRecordRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord.ExportOrderRecordRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord.ExportOrderRecordRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord.ExportOrderRecordRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 导出订单记录
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExportOrderRecordRequestBuilderGetQueryParameters 
        {
            /// <summary>终点名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("endStationName")]
            public string? EndStationName { get; set; }
#nullable restore
#else
            [QueryParameter("endStationName")]
            public string EndStationName { get; set; }
#endif
            /// <summary>终点编号</summary>
            [QueryParameter("endStationNo")]
            public int? EndStationNo { get; set; }
            /// <summary>订单执行时间查-结束  yyyy-MM-dd HH:mm:ss</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("endTime")]
            public string? EndTime { get; set; }
#nullable restore
#else
            [QueryParameter("endTime")]
            public string EndTime { get; set; }
#endif
            /// <summary>执行的车辆id：</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("executeVehicleKey")]
            public string? ExecuteVehicleKey { get; set; }
#nullable restore
#else
            [QueryParameter("executeVehicleKey")]
            public string ExecuteVehicleKey { get; set; }
#endif
            /// <summary>执行的车辆名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("executeVehicleName")]
            public string? ExecuteVehicleName { get; set; }
#nullable restore
#else
            [QueryParameter("executeVehicleName")]
            public string ExecuteVehicleName { get; set; }
#endif
            /// <summary>订单来源过滤器：1:WMS；2:FMS；</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filterBySource")]
            public string? FilterBySource { get; set; }
#nullable restore
#else
            [QueryParameter("filterBySource")]
            public string FilterBySource { get; set; }
#endif
            /// <summary>订单状态过滤器： 1 QUEUEING 队列中 , 2 CANCELLED 已取消, 3 EXECUTING 执行中, 4 FAILED 已失败, 5 SUCCESS 已完成, 6 DELETED  已移除, 7 PAUSED已暂停 ,8 SUSPENDED 已移除，9 HEAD 挂起, 10 队列优先执行</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filterByState")]
            public string[]? FilterByState { get; set; }
#nullable restore
#else
            [QueryParameter("filterByState")]
            public string[] FilterByState { get; set; }
#endif
            /// <summary>正序倒序（DESC为降序，ASC为正序）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>排序的列名</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderBy")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("orderBy")]
            public string OrderBy { get; set; }
#endif
            /// <summary>订单类型 1 NORMAL 工作订单, 2 CHARGE 充电订单 , 3 CMD 停靠订单 4 MAINTAIN 电池保养</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderType")]
            public string[]? OrderType { get; set; }
#nullable restore
#else
            [QueryParameter("orderType")]
            public string[] OrderType { get; set; }
#endif
            /// <summary>页码</summary>
            [QueryParameter("pageNum")]
            public int? PageNum { get; set; }
            /// <summary>页大小</summary>
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
            /// <summary>输入订单ID或订单名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>订单起点名称</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("startStationName")]
            public string? StartStationName { get; set; }
#nullable restore
#else
            [QueryParameter("startStationName")]
            public string StartStationName { get; set; }
#endif
            /// <summary>订单起点编号</summary>
            [QueryParameter("startStationNo")]
            public int? StartStationNo { get; set; }
            /// <summary>订单执行时间查询-开始  yyyy-MM-dd HH:mm:ss</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("startTime")]
            public string? StartTime { get; set; }
#nullable restore
#else
            [QueryParameter("startTime")]
            public string StartTime { get; set; }
#endif
            /// <summary>用户id</summary>
            [QueryParameter("userId")]
            public int? UserId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExportOrderRecordRequestBuilderGetRequestConfiguration : RequestConfiguration<global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.Old.ExportOrderRecord.ExportOrderRecordRequestBuilder.ExportOrderRecordRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
