// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Statistics.ChargeLocationCount
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\v1\statistics\chargeLocationCount
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChargeLocationCountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Statistics.ChargeLocationCount.ChargeLocationCountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChargeLocationCountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/statistics/chargeLocationCount", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Statistics.ChargeLocationCount.ChargeLocationCountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChargeLocationCountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/statistics/chargeLocationCount", rawUrl)
        {
        }
        /// <summary>
        /// 统计充电桩充电信息
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg_Of_u5145u7535u6869u7535u91cfu7edfu8ba1"/></returns>
        /// <param name="body">统计接受对象</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg_Of_u5145u7535u6869u7535u91cfu7edfu8ba1?> PostAsync(global::RIoT.Sdk.Generated.TaskApi.Models.U7edfu8ba1u63a5u53d7Object body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg_Of_u5145u7535u6869u7535u91cfu7edfu8ba1> PostAsync(global::RIoT.Sdk.Generated.TaskApi.Models.U7edfu8ba1u63a5u53d7Object body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg_Of_u5145u7535u6869u7535u91cfu7edfu8ba1>(requestInfo, global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg_Of_u5145u7535u6869u7535u91cfu7edfu8ba1.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 统计充电桩充电信息
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">统计接受对象</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::RIoT.Sdk.Generated.TaskApi.Models.U7edfu8ba1u63a5u53d7Object body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::RIoT.Sdk.Generated.TaskApi.Models.U7edfu8ba1u63a5u53d7Object body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Statistics.ChargeLocationCount.ChargeLocationCountRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Statistics.ChargeLocationCount.ChargeLocationCountRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Statistics.ChargeLocationCount.ChargeLocationCountRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChargeLocationCountRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
