// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Order.Api.Order.V1.Add;
using RIoT.Sdk.Generated.Order.Api.Order.V1.Operate;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderGroup;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecordChangeVehicle;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecordPriorityExec;
using RIoT.Sdk.Generated.Order.Api.Order.V1.TemplateAction;
using RIoT.Sdk.Generated.Order.Api.Order.V1.TemplateOrder;
using RIoT.Sdk.Generated.Order.Api.Order.V1.TemplateOrderTag;
using RIoT.Sdk.Generated.Order.Api.Order.V1.UpdateOrderTask;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.Order.Api.Order.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \api\order\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The add property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.Add.AddRequestBuilder Add
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.Add.AddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The operate property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.Operate.OperateRequestBuilder Operate
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.Operate.OperateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orderGroup property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderGroup.OrderGroupRequestBuilder OrderGroup
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderGroup.OrderGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orderRecord property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder OrderRecord
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.OrderRecordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orderRecordChangeVehicle property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecordChangeVehicle.OrderRecordChangeVehicleRequestBuilder OrderRecordChangeVehicle
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecordChangeVehicle.OrderRecordChangeVehicleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orderRecordPriorityExec property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecordPriorityExec.OrderRecordPriorityExecRequestBuilder OrderRecordPriorityExec
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecordPriorityExec.OrderRecordPriorityExecRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The templateAction property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.TemplateAction.TemplateActionRequestBuilder TemplateAction
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.TemplateAction.TemplateActionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The templateOrder property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.TemplateOrder.TemplateOrderRequestBuilder TemplateOrder
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.TemplateOrder.TemplateOrderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The templateOrderTag property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.TemplateOrderTag.TemplateOrderTagRequestBuilder TemplateOrderTag
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.TemplateOrderTag.TemplateOrderTagRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateOrderTask property</summary>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.UpdateOrderTask.UpdateOrderTaskRequestBuilder UpdateOrderTask
        {
            get => new global::RIoT.Sdk.Generated.Order.Api.Order.V1.UpdateOrderTask.UpdateOrderTaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/order/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/order/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
