// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.AllFileNames;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.BatchAdd;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.QueryCurSyncTasks;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.QueryDeviceByType;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.QuerySyncTasksByCondition;
using RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.SyncTasksExport;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\v1\vehicleSyncTask
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VehicleSyncTaskRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The allFileNames property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.AllFileNames.AllFileNamesRequestBuilder AllFileNames
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.AllFileNames.AllFileNamesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batchAdd property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.BatchAdd.BatchAddRequestBuilder BatchAdd
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.BatchAdd.BatchAddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queryCurSyncTasks property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.QueryCurSyncTasks.QueryCurSyncTasksRequestBuilder QueryCurSyncTasks
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.QueryCurSyncTasks.QueryCurSyncTasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queryDeviceByType property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.QueryDeviceByType.QueryDeviceByTypeRequestBuilder QueryDeviceByType
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.QueryDeviceByType.QueryDeviceByTypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The querySyncTasksByCondition property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.QuerySyncTasksByCondition.QuerySyncTasksByConditionRequestBuilder QuerySyncTasksByCondition
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.QuerySyncTasksByCondition.QuerySyncTasksByConditionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SyncTasksExport property</summary>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.SyncTasksExport.SyncTasksExportRequestBuilder SyncTasksExport
        {
            get => new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.SyncTasksExport.SyncTasksExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.VehicleSyncTaskRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VehicleSyncTaskRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/vehicleSyncTask", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.VehicleSyncTask.VehicleSyncTaskRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VehicleSyncTaskRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/vehicleSyncTask", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
