// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByUpperId.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByUpperId
{
    /// <summary>
    /// Builds and executes requests for operations under \api\order\v1\orderRecord\detailByUpperId
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DetailByUpperIdRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the RIoT.Sdk.Generated.Order.api.order.v1.orderRecord.detailByUpperId.item collection</summary>
        /// <param name="position">upperId</param>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByUpperId.Item.WithUpperItemRequestBuilder"/></returns>
        public global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByUpperId.Item.WithUpperItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("upperId", position);
                return new global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByUpperId.Item.WithUpperItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByUpperId.DetailByUpperIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DetailByUpperIdRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/order/v1/orderRecord/detailByUpperId", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Order.Api.Order.V1.OrderRecord.DetailByUpperId.DetailByUpperIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DetailByUpperIdRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/order/v1/orderRecord/detailByUpperId", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
