// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.Imap.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush
{
    /// <summary>
    /// Builds and executes requests for operations under \api\imap\v1\mapInfo\file\rePush
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RePushRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush.RePushRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RePushRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imap/v1/mapInfo/file/rePush?deviceId={deviceId}&mapSyncRecordId={mapSyncRecordId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush.RePushRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RePushRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imap/v1/mapInfo/file/rePush?deviceId={deviceId}&mapSyncRecordId={mapSyncRecordId}", rawUrl)
        {
        }
        /// <summary>
        /// 推送地图失败重试
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Void"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Void?> PostAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush.RePushRequestBuilder.RePushRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Void> PostAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush.RePushRequestBuilder.RePushRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Void>(requestInfo, global::RIoT.Sdk.Generated.Imap.Models.ResponseMsg_Of_Void.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 推送地图失败重试
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush.RePushRequestBuilder.RePushRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush.RePushRequestBuilder.RePushRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush.RePushRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush.RePushRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush.RePushRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 推送地图失败重试
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RePushRequestBuilderPostQueryParameters 
        {
            /// <summary>小车设备id</summary>
            [QueryParameter("deviceId")]
            public long? DeviceId { get; set; }
            /// <summary>同步记录Id</summary>
            [QueryParameter("mapSyncRecordId")]
            public int? MapSyncRecordId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RePushRequestBuilderPostRequestConfiguration : RequestConfiguration<global::RIoT.Sdk.Generated.Imap.Api.Imap.V1.MapInfo.FileNamespace.RePush.RePushRequestBuilder.RePushRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
