// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\v1\sros\importBatch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImportBatchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch.ImportBatchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImportBatchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/sros/importBatch?keys={keys}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch.ImportBatchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImportBatchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/v1/sros/importBatch?keys={keys}", rawUrl)
        {
        }
        /// <summary>
        /// 批量导入配置到SROS
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg?> PostAsync(Stream body, Action<RequestConfiguration<global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch.ImportBatchRequestBuilder.ImportBatchRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg> PostAsync(Stream body, Action<RequestConfiguration<global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch.ImportBatchRequestBuilder.ImportBatchRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg>(requestInfo, global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 批量导入配置到SROS
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Stream body, Action<RequestConfiguration<global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch.ImportBatchRequestBuilder.ImportBatchRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Stream body, Action<RequestConfiguration<global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch.ImportBatchRequestBuilder.ImportBatchRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetStreamContent(body, "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch.ImportBatchRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch.ImportBatchRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch.ImportBatchRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 批量导入配置到SROS
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ImportBatchRequestBuilderPostQueryParameters 
        {
            /// <summary>keys</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("keys")]
            public string? Keys { get; set; }
#nullable restore
#else
            [QueryParameter("keys")]
            public string Keys { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ImportBatchRequestBuilderPostRequestConfiguration : RequestConfiguration<global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.V1.Sros.ImportBatch.ImportBatchRequestBuilder.ImportBatchRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
