// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RIoT.Sdk.Generated.TaskApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey
{
    /// <summary>
    /// Builds and executes requests for operations under \api\task\vehicles\getVehicleInfoByDeviceKey
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetVehicleInfoByDeviceKeyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey.GetVehicleInfoByDeviceKeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetVehicleInfoByDeviceKeyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/vehicles/getVehicleInfoByDeviceKey{?key*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey.GetVehicleInfoByDeviceKeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetVehicleInfoByDeviceKeyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/task/vehicles/getVehicleInfoByDeviceKey{?key*}", rawUrl)
        {
        }
        /// <summary>
        /// 根据车辆的key查询车辆信息
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg_Of_u673au5668u4ebau5361u7247u8fd4u56deObject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg_Of_u673au5668u4ebau5361u7247u8fd4u56deObject?> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey.GetVehicleInfoByDeviceKeyRequestBuilder.GetVehicleInfoByDeviceKeyRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg_Of_u673au5668u4ebau5361u7247u8fd4u56deObject> GetAsync(Action<RequestConfiguration<global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey.GetVehicleInfoByDeviceKeyRequestBuilder.GetVehicleInfoByDeviceKeyRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg_Of_u673au5668u4ebau5361u7247u8fd4u56deObject>(requestInfo, global::RIoT.Sdk.Generated.TaskApi.Models.ResponseMsg_Of_u673au5668u4ebau5361u7247u8fd4u56deObject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// 根据车辆的key查询车辆信息
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey.GetVehicleInfoByDeviceKeyRequestBuilder.GetVehicleInfoByDeviceKeyRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey.GetVehicleInfoByDeviceKeyRequestBuilder.GetVehicleInfoByDeviceKeyRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey.GetVehicleInfoByDeviceKeyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey.GetVehicleInfoByDeviceKeyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey.GetVehicleInfoByDeviceKeyRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// 根据车辆的key查询车辆信息
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetVehicleInfoByDeviceKeyRequestBuilderGetQueryParameters 
        {
            /// <summary>key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("key")]
            public string? Key { get; set; }
#nullable restore
#else
            [QueryParameter("key")]
            public string Key { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetVehicleInfoByDeviceKeyRequestBuilderGetRequestConfiguration : RequestConfiguration<global::RIoT.Sdk.Generated.TaskApi.Api.TaskNamespace.Vehicles.GetVehicleInfoByDeviceKey.GetVehicleInfoByDeviceKeyRequestBuilder.GetVehicleInfoByDeviceKeyRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
